/*
 *
 * Copyright 2021-2024 Software Radio Systems Limited
 *
 * By using this file, you agree to the terms and conditions set
 * forth in the LICENSE file which can be found at the top level of
 * the distribution.
 *
 */

#pragma once

// This file was generated using the following MATLAB class on 30-10-2024 (seed 0):
//   + "srsChEqualizerUnittest.m"

#include "srsran/adt/complex.h"
#include "srsran/support/file_vector.h"

namespace srsran {

struct context_t {
  unsigned    nof_re, nof_layers, nof_rx_ports;
  float       noise_var;
  float       scaling;
  std::string equalizer_type;
};
struct test_case_t {
  context_t          context;
  file_vector<cf_t>  equalized_symbols;
  file_vector<float> equalized_noise_vars;
  file_vector<cf_t>  received_symbols;
  file_vector<cf_t>  ch_estimates;
};

static const std::vector<test_case_t> channel_equalizer_test_data = {
    // clang-format off
  {{12, 1, 1, 1.2094, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols0.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars0.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols0.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates0.dat"}},
  {{12, 1, 1, 0.96939, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols2.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars2.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols2.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates2.dat"}},
  {{12, 1, 1, 0.73992, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols4.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars4.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols4.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates4.dat"}},
  {{12, 1, 1, 0.80635, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols6.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars6.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols6.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates6.dat"}},
  {{12, 1, 1, 1.4289, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols8.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars8.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols8.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates8.dat"}},
  {{12, 1, 1, 0.52867, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols10.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars10.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols10.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates10.dat"}},
  {{12, 1, 2, 1.4063, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols12.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars12.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols12.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates12.dat"}},
  {{12, 1, 2, 0.6194, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols14.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars14.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols14.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates14.dat"}},
  {{12, 1, 2, 0.69986, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols16.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars16.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols16.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates16.dat"}},
  {{12, 1, 2, 0.5634, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols18.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars18.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols18.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates18.dat"}},
  {{12, 1, 2, 1.2814, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols20.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars20.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols20.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates20.dat"}},
  {{12, 1, 2, 1.0312, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols22.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars22.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols22.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates22.dat"}},
  {{12, 1, 3, 0.72377, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols24.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars24.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols24.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates24.dat"}},
  {{12, 1, 3, 0.83042, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols26.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars26.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols26.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates26.dat"}},
  {{12, 1, 3, 0.88888, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols28.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars28.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols28.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates28.dat"}},
  {{12, 1, 3, 1.3639, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols30.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars30.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols30.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates30.dat"}},
  {{12, 1, 3, 1.1723, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols32.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars32.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols32.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates32.dat"}},
  {{12, 1, 3, 1.4924, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols34.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars34.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols34.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates34.dat"}},
  {{12, 1, 4, 0.66689, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols36.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars36.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols36.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates36.dat"}},
  {{12, 1, 4, 0.8302, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols38.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars38.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols38.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates38.dat"}},
  {{12, 1, 4, 0.90683, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols40.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars40.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols40.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates40.dat"}},
  {{12, 1, 4, 0.92408, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols42.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars42.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols42.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates42.dat"}},
  {{12, 1, 4, 0.75375, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols44.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars44.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols44.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates44.dat"}},
  {{12, 1, 4, 0.58399, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols46.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars46.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols46.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates46.dat"}},
  {{12, 2, 2, 0.538, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols48.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars48.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols48.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates48.dat"}},
  {{12, 2, 2, 1.3859, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols50.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars50.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols50.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates50.dat"}},
  {{12, 2, 2, 1.1877, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols52.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars52.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols52.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates52.dat"}},
  {{12, 2, 2, 0.60371, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols54.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars54.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols54.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates54.dat"}},
  {{12, 2, 2, 0.73338, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols56.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars56.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols56.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates56.dat"}},
  {{12, 2, 2, 0.9494, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols58.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars58.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols58.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates58.dat"}},
  {{12, 2, 4, 1.1617, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols60.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars60.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols60.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates60.dat"}},
  {{12, 2, 4, 0.96881, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols62.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars62.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols62.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates62.dat"}},
  {{12, 2, 4, 0.6577, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols64.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars64.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols64.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates64.dat"}},
  {{12, 2, 4, 0.50736, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols66.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars66.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols66.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates66.dat"}},
  {{12, 2, 4, 1.0069, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols68.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars68.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols68.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates68.dat"}},
  {{12, 2, 4, 0.76368, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols70.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars70.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols70.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates70.dat"}},
  {{12, 3, 4, 0.64595, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols72.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars72.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols72.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates72.dat"}},
  {{12, 3, 4, 1.4277, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols74.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars74.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols74.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates74.dat"}},
  {{12, 3, 4, 0.86573, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols76.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars76.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols76.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates76.dat"}},
  {{12, 3, 4, 0.62542, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols78.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars78.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols78.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates78.dat"}},
  {{12, 3, 4, 1.374, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols80.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars80.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols80.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates80.dat"}},
  {{12, 3, 4, 0.53093, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols82.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars82.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols82.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates82.dat"}},
  {{12, 4, 4, 0.55244, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols84.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars84.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols84.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates84.dat"}},
  {{12, 4, 4, 0.70667, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols86.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars86.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols86.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates86.dat"}},
  {{12, 4, 4, 1.0793, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols88.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars88.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols88.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates88.dat"}},
  {{12, 4, 4, 0.80486, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols90.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars90.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols90.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates90.dat"}},
  {{12, 4, 4, 1.0133, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols92.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars92.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols92.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates92.dat"}},
  {{12, 4, 4, 0.98787, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols94.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars94.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols94.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates94.dat"}},
  {{123, 1, 1, 1.2551, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols96.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars96.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols96.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates96.dat"}},
  {{123, 1, 1, 1.1721, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols98.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars98.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols98.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates98.dat"}},
  {{123, 1, 1, 0.56838, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols100.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars100.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols100.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates100.dat"}},
  {{123, 1, 1, 0.92984, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols102.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars102.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols102.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates102.dat"}},
  {{123, 1, 1, 0.94414, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols104.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars104.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols104.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates104.dat"}},
  {{123, 1, 1, 1.1354, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols106.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars106.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols106.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates106.dat"}},
  {{123, 1, 2, 1.3772, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols108.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars108.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols108.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates108.dat"}},
  {{123, 1, 2, 0.9402, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols110.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars110.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols110.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates110.dat"}},
  {{123, 1, 2, 0.88842, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols112.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars112.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols112.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates112.dat"}},
  {{123, 1, 2, 0.7754, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols114.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars114.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols114.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates114.dat"}},
  {{123, 1, 2, 1.0888, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols116.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars116.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols116.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates116.dat"}},
  {{123, 1, 2, 1.1649, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols118.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars118.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols118.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates118.dat"}},
  {{123, 1, 3, 1.4656, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols120.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars120.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols120.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates120.dat"}},
  {{123, 1, 3, 1.2798, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols122.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars122.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols122.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates122.dat"}},
  {{123, 1, 3, 0.95022, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols124.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars124.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols124.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates124.dat"}},
  {{123, 1, 3, 1.2338, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols126.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars126.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols126.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates126.dat"}},
  {{123, 1, 3, 0.52166, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols128.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars128.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols128.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates128.dat"}},
  {{123, 1, 3, 1.113, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols130.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars130.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols130.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates130.dat"}},
  {{123, 1, 4, 1.0704, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols132.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars132.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols132.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates132.dat"}},
  {{123, 1, 4, 0.53834, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols134.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars134.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols134.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates134.dat"}},
  {{123, 1, 4, 1.2245, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols136.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars136.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols136.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates136.dat"}},
  {{123, 1, 4, 0.67394, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols138.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars138.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols138.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates138.dat"}},
  {{123, 1, 4, 0.94875, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols140.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars140.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols140.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates140.dat"}},
  {{123, 1, 4, 1.0117, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols142.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars142.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols142.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates142.dat"}},
  {{123, 2, 2, 1.4714, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols144.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars144.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols144.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates144.dat"}},
  {{123, 2, 2, 0.52387, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols146.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars146.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols146.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates146.dat"}},
  {{123, 2, 2, 0.96166, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols148.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars148.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols148.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates148.dat"}},
  {{123, 2, 2, 0.63389, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols150.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars150.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols150.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates150.dat"}},
  {{123, 2, 2, 0.93844, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols152.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars152.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols152.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates152.dat"}},
  {{123, 2, 2, 1.1995, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols154.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars154.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols154.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates154.dat"}},
  {{123, 2, 4, 0.81616, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols156.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars156.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols156.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates156.dat"}},
  {{123, 2, 4, 1.3773, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols158.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars158.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols158.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates158.dat"}},
  {{123, 2, 4, 0.78607, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols160.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars160.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols160.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates160.dat"}},
  {{123, 2, 4, 1.4465, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols162.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars162.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols162.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates162.dat"}},
  {{123, 2, 4, 0.92831, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols164.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars164.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols164.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates164.dat"}},
  {{123, 2, 4, 1.2488, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols166.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars166.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols166.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates166.dat"}},
  {{123, 3, 4, 0.94925, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols168.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars168.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols168.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates168.dat"}},
  {{123, 3, 4, 1.3845, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols170.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars170.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols170.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates170.dat"}},
  {{123, 3, 4, 0.84941, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols172.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars172.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols172.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates172.dat"}},
  {{123, 3, 4, 0.88369, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols174.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars174.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols174.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates174.dat"}},
  {{123, 3, 4, 1.1078, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols176.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars176.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols176.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates176.dat"}},
  {{123, 3, 4, 0.60663, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols178.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars178.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols178.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates178.dat"}},
  {{123, 4, 4, 0.84477, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols180.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars180.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols180.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates180.dat"}},
  {{123, 4, 4, 0.80021, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols182.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars182.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols182.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates182.dat"}},
  {{123, 4, 4, 0.72526, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols184.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars184.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols184.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates184.dat"}},
  {{123, 4, 4, 0.69193, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols186.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars186.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols186.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates186.dat"}},
  {{123, 4, 4, 1.1803, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols188.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars188.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols188.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates188.dat"}},
  {{123, 4, 4, 0.57174, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols190.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars190.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols190.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates190.dat"}},
  {{1000, 1, 1, 1.3126, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols192.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars192.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols192.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates192.dat"}},
  {{1000, 1, 1, 1.1317, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols194.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars194.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols194.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates194.dat"}},
  {{1000, 1, 1, 0.91506, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols196.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars196.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols196.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates196.dat"}},
  {{1000, 1, 1, 0.96117, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols198.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars198.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols198.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates198.dat"}},
  {{1000, 1, 1, 0.82829, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols200.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars200.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols200.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates200.dat"}},
  {{1000, 1, 1, 0.66337, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols202.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars202.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols202.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates202.dat"}},
  {{1000, 1, 2, 0.98357, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols204.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars204.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols204.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates204.dat"}},
  {{1000, 1, 2, 1.1373, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols206.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars206.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols206.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates206.dat"}},
  {{1000, 1, 2, 0.88062, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols208.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars208.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols208.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates208.dat"}},
  {{1000, 1, 2, 0.60396, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols210.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars210.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols210.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates210.dat"}},
  {{1000, 1, 2, 1.2035, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols212.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars212.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols212.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates212.dat"}},
  {{1000, 1, 2, 1.2054, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols214.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars214.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols214.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates214.dat"}},
  {{1000, 1, 3, 1.3278, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols216.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars216.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols216.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates216.dat"}},
  {{1000, 1, 3, 0.66418, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols218.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars218.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols218.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates218.dat"}},
  {{1000, 1, 3, 1.3527, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols220.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars220.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols220.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates220.dat"}},
  {{1000, 1, 3, 1.1065, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols222.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars222.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols222.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates222.dat"}},
  {{1000, 1, 3, 0.99419, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols224.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars224.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols224.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates224.dat"}},
  {{1000, 1, 3, 0.60139, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols226.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars226.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols226.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates226.dat"}},
  {{1000, 1, 4, 0.64839, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols228.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars228.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols228.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates228.dat"}},
  {{1000, 1, 4, 1.3774, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols230.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars230.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols230.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates230.dat"}},
  {{1000, 1, 4, 0.77943, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols232.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars232.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols232.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates232.dat"}},
  {{1000, 1, 4, 1.1469, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols234.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars234.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols234.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates234.dat"}},
  {{1000, 1, 4, 1.3728, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols236.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars236.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols236.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates236.dat"}},
  {{1000, 1, 4, 1.3852, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols238.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars238.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols238.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates238.dat"}},
  {{1000, 2, 2, 1.3243, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols240.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars240.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols240.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates240.dat"}},
  {{1000, 2, 2, 1.0728, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols242.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars242.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols242.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates242.dat"}},
  {{1000, 2, 2, 0.92915, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols244.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars244.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols244.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates244.dat"}},
  {{1000, 2, 2, 0.97321, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols246.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars246.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols246.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates246.dat"}},
  {{1000, 2, 2, 1.2893, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols248.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars248.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols248.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates248.dat"}},
  {{1000, 2, 2, 0.63602, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols250.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars250.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols250.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates250.dat"}},
  {{1000, 2, 4, 1.0267, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols252.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars252.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols252.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates252.dat"}},
  {{1000, 2, 4, 0.96395, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols254.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars254.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols254.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates254.dat"}},
  {{1000, 2, 4, 0.91864, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols256.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars256.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols256.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates256.dat"}},
  {{1000, 2, 4, 0.50686, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols258.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars258.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols258.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates258.dat"}},
  {{1000, 2, 4, 1.4626, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols260.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars260.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols260.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates260.dat"}},
  {{1000, 2, 4, 0.63135, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols262.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars262.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols262.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates262.dat"}},
  {{1000, 3, 4, 1.4109, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols264.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars264.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols264.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates264.dat"}},
  {{1000, 3, 4, 0.93746, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols266.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars266.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols266.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates266.dat"}},
  {{1000, 3, 4, 0.61719, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols268.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars268.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols268.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates268.dat"}},
  {{1000, 3, 4, 0.92604, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols270.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars270.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols270.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates270.dat"}},
  {{1000, 3, 4, 1.2671, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols272.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars272.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols272.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates272.dat"}},
  {{1000, 3, 4, 0.67037, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols274.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars274.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols274.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates274.dat"}},
  {{1000, 4, 4, 1.3331, 1, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols276.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars276.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols276.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates276.dat"}},
  {{1000, 4, 4, 0.56418, 1.4142, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols278.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars278.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols278.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates278.dat"}},
  {{1000, 4, 4, 1.1597, 0.5, "MMSE"}, {"test_data/channel_equalizer_test_output_eq_symbols280.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars280.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols280.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates280.dat"}},
  {{1000, 4, 4, 0.52164, 1, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols282.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars282.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols282.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates282.dat"}},
  {{1000, 4, 4, 0.68873, 1.4142, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols284.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars284.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols284.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates284.dat"}},
  {{1000, 4, 4, 1.3982, 0.5, "ZF"}, {"test_data/channel_equalizer_test_output_eq_symbols286.dat"}, {"test_data/channel_equalizer_test_output_eq_noise_vars286.dat"}, {"test_data/channel_equalizer_test_input_rx_symbols286.dat"}, {"test_data/channel_equalizer_test_input_ch_estimates286.dat"}},
    // clang-format on
};

} // namespace srsran
