{
 "title": "srsRAN Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=/public/img/logo.png />"
   }
  },
  {
   "title": "Num Cells with Active UEs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH last_point AS ( SELECT MAX(time) AS last_time FROM ue WHERE time BETWEEN $__timeFrom AND $__timeTo )\nSELECT COUNT(DISTINCT(pci)) FROM ue CROSS JOIN last_point WHERE time >= last_point.last_time - INTERVAL '5s' AND time <= last_point.last_time"
    }
   ]
  },
  {
   "title": "Active UEs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH last_point AS ( SELECT MAX(time) AS last_time FROM ue WHERE time BETWEEN $__timeFrom AND $__timeTo )\nSELECT COUNT(DISTINCT(rnti)) FROM ue CROSS JOIN last_point WHERE time >= last_point.last_time - INTERVAL '5s' AND time <= last_point.last_time"
    }
   ]
  },
  {
   "title": "Current Total Downlink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, SUM(dl_brate) FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Maximum Total Downlink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(total_dl_brate) FROM ( SELECT SUM(dl_brate) AS total_dl_brate FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo GROUP BY time ORDER BY time )"
    }
   ]
  },
  { "title": "Bitrate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Downlink Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_brate, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Uplink Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ul_brate, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  { "title": "BLER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Downlink BLER",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT (100.0 * dl_nof_nok) / (dl_nof_ok + dl_nof_nok), time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Uplink BLER",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT (100.0 * ul_nof_nok) / (ul_nof_ok + ul_nof_nok), time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  { "title": "Average MCS index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Downlink MCS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_mcs, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Uplink MCS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ul_mcs, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  { "title": "Buffer State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "DL Buffer Occupancy Reports",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_bs, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "UL Buffer Status Reports",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT bsr, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  { "title": "Rank Indicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "DL RI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_ri, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "UL RI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ul_ri, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  { "title": "More", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT cqi, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Uplink SNR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT pusch_snr_db, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Time Advance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ta_ns, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "Uplink RSRP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT pusch_rsrp_db, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  },
  {
   "title": "PHR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT last_phr, time, pci, rnti FROM ue WHERE time >= $__timeFrom AND time <= $__timeTo ORDER BY time"
    }
   ]
  }
 ]
}