{
 "title": "RRC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gnb_du_id",
    "label": "gNB DU ID",
    "query": {
     "query": "SELECT gnb_du_id from rrcs GROUP BY gnb_du_id"
    }
   }
  ]
 },
 "panels": [
  { "title": "RRC connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean",
   "type": "stat",
   "description": "Mean number of RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"rrc_connection_number_max_nof_rrc_connections\" AS 'max', \"rrc_connection_number_mean_nof_rrc_connections\" AS 'mean' FROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_du_id\" == '$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "description": "Maximum number of RRC connections",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "title": "RRC connection establishment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Attempted",
   "type": "stat",
   "description": "Attempted RRC connection establishments",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_emergency\" AS 'emergency',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_data\" AS 'mo_data',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_mt_access\" AS 'mt_access',\n    \"rrc_connection_establishment_attempted_rrc_connection_establishments_unknown\" AS 'unknown'\n              \nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND gnb_du_id ='$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Successful RRC connection establishments",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_emergency\" AS 'emergency',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_high_prio_access\" AS 'high_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mcs_prio_access\" AS 'mcs_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_data\" AS 'mo_data',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_sig\" AS 'mo_sig',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_sms\" AS 'mo_sms',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_video_call\" AS 'mo_video_call',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mo_voice_call\" AS 'mo_voice_call',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mps_prio_access\" AS 'mps_prio_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_mt_access\" AS 'mt_access',\n    \"rrc_connection_establishment_successful_rrc_connection_establishments_unknown\" AS 'unknown'\n\nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_du_id\" == '$gnb_du_id'\n"
    }
   ]
  },
  {
   "title": "RRC connection establishment (details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attempted (detail)",
     "type": "bargauge",
     "description": "Attempted RRC connection establishments (detail)",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 6 }
     ]
    },
    {
     "title": "Successful (details)",
     "type": "bargauge",
     "description": "Successful RRC connection establishments (details)",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 7 }
     ]
    }
   ]
  },
  { "title": "RRC connection reestablishment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Attempted",
   "type": "stat",
   "description": "Attempted RRC connection reestablishments",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    \"rrc_connection_reestablishment_attempted_rrc_connection_reestablishments\",\n    \"rrc_connection_reestablishment_successful_rrc_connection_reestablishments_with_ue_context\",\n    \"rrc_connection_reestablishment_successful_rrc_connection_reestablishments_without_ue_context\"\nFROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"gnb_du_id\" == '$gnb_du_id'"
    }
   ]
  },
  {
   "title": "Successful with ue context",
   "type": "stat",
   "description": "Successful RRC connection reestablishments with ue context",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Successful without ue context",
   "type": "stat",
   "description": "Successful RRC connection reestablishments without ue context",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  { "title": "Handover (all DUs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requested",
   "type": "stat",
   "description": "Number of handover executions requested",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"nof_handover_executions_requested\", \"nof_successful_handover_executions\" FROM \"cu_cp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Number of successful handover executions",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  }
 ]
}