/*
 *
 * Copyright 2021-2023 Software Radio Systems Limited
 *
 * By using this file, you agree to the terms and conditions set
 * forth in the LICENSE file which can be found at the top level of
 * the distribution.
 *
 */

#pragma once

// This file was generated using the following MATLAB class on 14-03-2023:
//   + "srsPRACHDemodulatorUnittest.m"

#include "srsran/phy/lower/modulation/ofdm_prach_demodulator.h"
#include "srsran/support/file_vector.h"

namespace srsran {

struct prach_context {
  unsigned                              dft_size_15kHz;
  ofdm_prach_demodulator::configuration config;
};

struct test_case_t {
  prach_context     context;
  file_vector<cf_t> input;
  file_vector<cf_t> output;
};

static const std::vector<test_case_t> ofdm_prach_demodulator_test_data = {
    // clang-format off
  {{1024, {to_prach_format_type("0"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input0.dat"}, {"test_data/ofdm_prach_demodulator_test_output0.dat"}},
  {{1024, {to_prach_format_type("0"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input1.dat"}, {"test_data/ofdm_prach_demodulator_test_output1.dat"}},
  {{1024, {to_prach_format_type("0"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input2.dat"}, {"test_data/ofdm_prach_demodulator_test_output2.dat"}},
  {{1024, {to_prach_format_type("1"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input3.dat"}, {"test_data/ofdm_prach_demodulator_test_output3.dat"}},
  {{1024, {to_prach_format_type("1"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input4.dat"}, {"test_data/ofdm_prach_demodulator_test_output4.dat"}},
  {{1024, {to_prach_format_type("1"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input5.dat"}, {"test_data/ofdm_prach_demodulator_test_output5.dat"}},
  {{1024, {to_prach_format_type("2"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input6.dat"}, {"test_data/ofdm_prach_demodulator_test_output6.dat"}},
  {{1024, {to_prach_format_type("2"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input7.dat"}, {"test_data/ofdm_prach_demodulator_test_output7.dat"}},
  {{1024, {to_prach_format_type("2"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input8.dat"}, {"test_data/ofdm_prach_demodulator_test_output8.dat"}},
  {{1024, {to_prach_format_type("3"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input9.dat"}, {"test_data/ofdm_prach_demodulator_test_output9.dat"}},
  {{1024, {to_prach_format_type("3"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input10.dat"}, {"test_data/ofdm_prach_demodulator_test_output10.dat"}},
  {{1024, {to_prach_format_type("3"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input11.dat"}, {"test_data/ofdm_prach_demodulator_test_output11.dat"}},
  {{1024, {to_prach_format_type("A1"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input12.dat"}, {"test_data/ofdm_prach_demodulator_test_output12.dat"}},
  {{1024, {to_prach_format_type("A1"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input13.dat"}, {"test_data/ofdm_prach_demodulator_test_output13.dat"}},
  {{1024, {to_prach_format_type("A1"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input14.dat"}, {"test_data/ofdm_prach_demodulator_test_output14.dat"}},
  {{1024, {to_prach_format_type("A1"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input15.dat"}, {"test_data/ofdm_prach_demodulator_test_output15.dat"}},
  {{1024, {to_prach_format_type("A1"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input16.dat"}, {"test_data/ofdm_prach_demodulator_test_output16.dat"}},
  {{1024, {to_prach_format_type("A1"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input17.dat"}, {"test_data/ofdm_prach_demodulator_test_output17.dat"}},
  {{1024, {to_prach_format_type("A2"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input18.dat"}, {"test_data/ofdm_prach_demodulator_test_output18.dat"}},
  {{1024, {to_prach_format_type("A2"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input19.dat"}, {"test_data/ofdm_prach_demodulator_test_output19.dat"}},
  {{1024, {to_prach_format_type("A2"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input20.dat"}, {"test_data/ofdm_prach_demodulator_test_output20.dat"}},
  {{1024, {to_prach_format_type("A2"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input21.dat"}, {"test_data/ofdm_prach_demodulator_test_output21.dat"}},
  {{1024, {to_prach_format_type("A2"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input22.dat"}, {"test_data/ofdm_prach_demodulator_test_output22.dat"}},
  {{1024, {to_prach_format_type("A2"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input23.dat"}, {"test_data/ofdm_prach_demodulator_test_output23.dat"}},
  {{1024, {to_prach_format_type("A3"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input24.dat"}, {"test_data/ofdm_prach_demodulator_test_output24.dat"}},
  {{1024, {to_prach_format_type("A3"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input25.dat"}, {"test_data/ofdm_prach_demodulator_test_output25.dat"}},
  {{1024, {to_prach_format_type("A3"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input26.dat"}, {"test_data/ofdm_prach_demodulator_test_output26.dat"}},
  {{1024, {to_prach_format_type("A3"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input27.dat"}, {"test_data/ofdm_prach_demodulator_test_output27.dat"}},
  {{1024, {to_prach_format_type("A3"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input28.dat"}, {"test_data/ofdm_prach_demodulator_test_output28.dat"}},
  {{1024, {to_prach_format_type("A3"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input29.dat"}, {"test_data/ofdm_prach_demodulator_test_output29.dat"}},
  {{1024, {to_prach_format_type("B1"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input30.dat"}, {"test_data/ofdm_prach_demodulator_test_output30.dat"}},
  {{1024, {to_prach_format_type("B1"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input31.dat"}, {"test_data/ofdm_prach_demodulator_test_output31.dat"}},
  {{1024, {to_prach_format_type("B1"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input32.dat"}, {"test_data/ofdm_prach_demodulator_test_output32.dat"}},
  {{1024, {to_prach_format_type("B4"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input33.dat"}, {"test_data/ofdm_prach_demodulator_test_output33.dat"}},
  {{1024, {to_prach_format_type("B4"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input34.dat"}, {"test_data/ofdm_prach_demodulator_test_output34.dat"}},
  {{1024, {to_prach_format_type("B4"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input35.dat"}, {"test_data/ofdm_prach_demodulator_test_output35.dat"}},
  {{1024, {to_prach_format_type("C0"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input36.dat"}, {"test_data/ofdm_prach_demodulator_test_output36.dat"}},
  {{1024, {to_prach_format_type("C0"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input37.dat"}, {"test_data/ofdm_prach_demodulator_test_output37.dat"}},
  {{1024, {to_prach_format_type("C0"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input38.dat"}, {"test_data/ofdm_prach_demodulator_test_output38.dat"}},
  {{1024, {to_prach_format_type("C2"), 0, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input39.dat"}, {"test_data/ofdm_prach_demodulator_test_output39.dat"}},
  {{1024, {to_prach_format_type("C2"), 13, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input40.dat"}, {"test_data/ofdm_prach_demodulator_test_output40.dat"}},
  {{1024, {to_prach_format_type("C2"), 28, 52, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input41.dat"}, {"test_data/ofdm_prach_demodulator_test_output41.dat"}},
  {{2048, {to_prach_format_type("0"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input42.dat"}, {"test_data/ofdm_prach_demodulator_test_output42.dat"}},
  {{2048, {to_prach_format_type("0"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input43.dat"}, {"test_data/ofdm_prach_demodulator_test_output43.dat"}},
  {{2048, {to_prach_format_type("0"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input44.dat"}, {"test_data/ofdm_prach_demodulator_test_output44.dat"}},
  {{2048, {to_prach_format_type("1"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input45.dat"}, {"test_data/ofdm_prach_demodulator_test_output45.dat"}},
  {{2048, {to_prach_format_type("1"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input46.dat"}, {"test_data/ofdm_prach_demodulator_test_output46.dat"}},
  {{2048, {to_prach_format_type("1"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input47.dat"}, {"test_data/ofdm_prach_demodulator_test_output47.dat"}},
  {{2048, {to_prach_format_type("2"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input48.dat"}, {"test_data/ofdm_prach_demodulator_test_output48.dat"}},
  {{2048, {to_prach_format_type("2"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input49.dat"}, {"test_data/ofdm_prach_demodulator_test_output49.dat"}},
  {{2048, {to_prach_format_type("2"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input50.dat"}, {"test_data/ofdm_prach_demodulator_test_output50.dat"}},
  {{2048, {to_prach_format_type("3"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input51.dat"}, {"test_data/ofdm_prach_demodulator_test_output51.dat"}},
  {{2048, {to_prach_format_type("3"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input52.dat"}, {"test_data/ofdm_prach_demodulator_test_output52.dat"}},
  {{2048, {to_prach_format_type("3"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input53.dat"}, {"test_data/ofdm_prach_demodulator_test_output53.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input54.dat"}, {"test_data/ofdm_prach_demodulator_test_output54.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input55.dat"}, {"test_data/ofdm_prach_demodulator_test_output55.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input56.dat"}, {"test_data/ofdm_prach_demodulator_test_output56.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input57.dat"}, {"test_data/ofdm_prach_demodulator_test_output57.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input58.dat"}, {"test_data/ofdm_prach_demodulator_test_output58.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input59.dat"}, {"test_data/ofdm_prach_demodulator_test_output59.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input60.dat"}, {"test_data/ofdm_prach_demodulator_test_output60.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input61.dat"}, {"test_data/ofdm_prach_demodulator_test_output61.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input62.dat"}, {"test_data/ofdm_prach_demodulator_test_output62.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input63.dat"}, {"test_data/ofdm_prach_demodulator_test_output63.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input64.dat"}, {"test_data/ofdm_prach_demodulator_test_output64.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input65.dat"}, {"test_data/ofdm_prach_demodulator_test_output65.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input66.dat"}, {"test_data/ofdm_prach_demodulator_test_output66.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input67.dat"}, {"test_data/ofdm_prach_demodulator_test_output67.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input68.dat"}, {"test_data/ofdm_prach_demodulator_test_output68.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input69.dat"}, {"test_data/ofdm_prach_demodulator_test_output69.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input70.dat"}, {"test_data/ofdm_prach_demodulator_test_output70.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input71.dat"}, {"test_data/ofdm_prach_demodulator_test_output71.dat"}},
  {{2048, {to_prach_format_type("B1"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input72.dat"}, {"test_data/ofdm_prach_demodulator_test_output72.dat"}},
  {{2048, {to_prach_format_type("B1"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input73.dat"}, {"test_data/ofdm_prach_demodulator_test_output73.dat"}},
  {{2048, {to_prach_format_type("B1"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input74.dat"}, {"test_data/ofdm_prach_demodulator_test_output74.dat"}},
  {{2048, {to_prach_format_type("B4"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input75.dat"}, {"test_data/ofdm_prach_demodulator_test_output75.dat"}},
  {{2048, {to_prach_format_type("B4"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input76.dat"}, {"test_data/ofdm_prach_demodulator_test_output76.dat"}},
  {{2048, {to_prach_format_type("B4"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input77.dat"}, {"test_data/ofdm_prach_demodulator_test_output77.dat"}},
  {{2048, {to_prach_format_type("C0"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input78.dat"}, {"test_data/ofdm_prach_demodulator_test_output78.dat"}},
  {{2048, {to_prach_format_type("C0"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input79.dat"}, {"test_data/ofdm_prach_demodulator_test_output79.dat"}},
  {{2048, {to_prach_format_type("C0"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input80.dat"}, {"test_data/ofdm_prach_demodulator_test_output80.dat"}},
  {{2048, {to_prach_format_type("C2"), 0, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input81.dat"}, {"test_data/ofdm_prach_demodulator_test_output81.dat"}},
  {{2048, {to_prach_format_type("C2"), 13, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input82.dat"}, {"test_data/ofdm_prach_demodulator_test_output82.dat"}},
  {{2048, {to_prach_format_type("C2"), 28, 79, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input83.dat"}, {"test_data/ofdm_prach_demodulator_test_output83.dat"}},
  {{2048, {to_prach_format_type("0"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input84.dat"}, {"test_data/ofdm_prach_demodulator_test_output84.dat"}},
  {{2048, {to_prach_format_type("0"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input85.dat"}, {"test_data/ofdm_prach_demodulator_test_output85.dat"}},
  {{2048, {to_prach_format_type("0"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input86.dat"}, {"test_data/ofdm_prach_demodulator_test_output86.dat"}},
  {{2048, {to_prach_format_type("1"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input87.dat"}, {"test_data/ofdm_prach_demodulator_test_output87.dat"}},
  {{2048, {to_prach_format_type("1"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input88.dat"}, {"test_data/ofdm_prach_demodulator_test_output88.dat"}},
  {{2048, {to_prach_format_type("1"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input89.dat"}, {"test_data/ofdm_prach_demodulator_test_output89.dat"}},
  {{2048, {to_prach_format_type("2"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input90.dat"}, {"test_data/ofdm_prach_demodulator_test_output90.dat"}},
  {{2048, {to_prach_format_type("2"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input91.dat"}, {"test_data/ofdm_prach_demodulator_test_output91.dat"}},
  {{2048, {to_prach_format_type("2"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input92.dat"}, {"test_data/ofdm_prach_demodulator_test_output92.dat"}},
  {{2048, {to_prach_format_type("3"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input93.dat"}, {"test_data/ofdm_prach_demodulator_test_output93.dat"}},
  {{2048, {to_prach_format_type("3"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input94.dat"}, {"test_data/ofdm_prach_demodulator_test_output94.dat"}},
  {{2048, {to_prach_format_type("3"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input95.dat"}, {"test_data/ofdm_prach_demodulator_test_output95.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input96.dat"}, {"test_data/ofdm_prach_demodulator_test_output96.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input97.dat"}, {"test_data/ofdm_prach_demodulator_test_output97.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input98.dat"}, {"test_data/ofdm_prach_demodulator_test_output98.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input99.dat"}, {"test_data/ofdm_prach_demodulator_test_output99.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input100.dat"}, {"test_data/ofdm_prach_demodulator_test_output100.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input101.dat"}, {"test_data/ofdm_prach_demodulator_test_output101.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input102.dat"}, {"test_data/ofdm_prach_demodulator_test_output102.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input103.dat"}, {"test_data/ofdm_prach_demodulator_test_output103.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input104.dat"}, {"test_data/ofdm_prach_demodulator_test_output104.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input105.dat"}, {"test_data/ofdm_prach_demodulator_test_output105.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input106.dat"}, {"test_data/ofdm_prach_demodulator_test_output106.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input107.dat"}, {"test_data/ofdm_prach_demodulator_test_output107.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input108.dat"}, {"test_data/ofdm_prach_demodulator_test_output108.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input109.dat"}, {"test_data/ofdm_prach_demodulator_test_output109.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input110.dat"}, {"test_data/ofdm_prach_demodulator_test_output110.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input111.dat"}, {"test_data/ofdm_prach_demodulator_test_output111.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input112.dat"}, {"test_data/ofdm_prach_demodulator_test_output112.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input113.dat"}, {"test_data/ofdm_prach_demodulator_test_output113.dat"}},
  {{2048, {to_prach_format_type("B1"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input114.dat"}, {"test_data/ofdm_prach_demodulator_test_output114.dat"}},
  {{2048, {to_prach_format_type("B1"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input115.dat"}, {"test_data/ofdm_prach_demodulator_test_output115.dat"}},
  {{2048, {to_prach_format_type("B1"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input116.dat"}, {"test_data/ofdm_prach_demodulator_test_output116.dat"}},
  {{2048, {to_prach_format_type("B4"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input117.dat"}, {"test_data/ofdm_prach_demodulator_test_output117.dat"}},
  {{2048, {to_prach_format_type("B4"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input118.dat"}, {"test_data/ofdm_prach_demodulator_test_output118.dat"}},
  {{2048, {to_prach_format_type("B4"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input119.dat"}, {"test_data/ofdm_prach_demodulator_test_output119.dat"}},
  {{2048, {to_prach_format_type("C0"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input120.dat"}, {"test_data/ofdm_prach_demodulator_test_output120.dat"}},
  {{2048, {to_prach_format_type("C0"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input121.dat"}, {"test_data/ofdm_prach_demodulator_test_output121.dat"}},
  {{2048, {to_prach_format_type("C0"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input122.dat"}, {"test_data/ofdm_prach_demodulator_test_output122.dat"}},
  {{2048, {to_prach_format_type("C2"), 0, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input123.dat"}, {"test_data/ofdm_prach_demodulator_test_output123.dat"}},
  {{2048, {to_prach_format_type("C2"), 13, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input124.dat"}, {"test_data/ofdm_prach_demodulator_test_output124.dat"}},
  {{2048, {to_prach_format_type("C2"), 28, 106, subcarrier_spacing::kHz15}}, {"test_data/ofdm_prach_demodulator_test_input125.dat"}, {"test_data/ofdm_prach_demodulator_test_output125.dat"}},
  {{2048, {to_prach_format_type("0"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input126.dat"}, {"test_data/ofdm_prach_demodulator_test_output126.dat"}},
  {{2048, {to_prach_format_type("0"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input127.dat"}, {"test_data/ofdm_prach_demodulator_test_output127.dat"}},
  {{2048, {to_prach_format_type("0"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input128.dat"}, {"test_data/ofdm_prach_demodulator_test_output128.dat"}},
  {{2048, {to_prach_format_type("1"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input129.dat"}, {"test_data/ofdm_prach_demodulator_test_output129.dat"}},
  {{2048, {to_prach_format_type("1"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input130.dat"}, {"test_data/ofdm_prach_demodulator_test_output130.dat"}},
  {{2048, {to_prach_format_type("1"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input131.dat"}, {"test_data/ofdm_prach_demodulator_test_output131.dat"}},
  {{2048, {to_prach_format_type("2"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input132.dat"}, {"test_data/ofdm_prach_demodulator_test_output132.dat"}},
  {{2048, {to_prach_format_type("2"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input133.dat"}, {"test_data/ofdm_prach_demodulator_test_output133.dat"}},
  {{2048, {to_prach_format_type("2"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input134.dat"}, {"test_data/ofdm_prach_demodulator_test_output134.dat"}},
  {{2048, {to_prach_format_type("3"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input135.dat"}, {"test_data/ofdm_prach_demodulator_test_output135.dat"}},
  {{2048, {to_prach_format_type("3"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input136.dat"}, {"test_data/ofdm_prach_demodulator_test_output136.dat"}},
  {{2048, {to_prach_format_type("3"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input137.dat"}, {"test_data/ofdm_prach_demodulator_test_output137.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input138.dat"}, {"test_data/ofdm_prach_demodulator_test_output138.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input139.dat"}, {"test_data/ofdm_prach_demodulator_test_output139.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input140.dat"}, {"test_data/ofdm_prach_demodulator_test_output140.dat"}},
  {{2048, {to_prach_format_type("A1"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input141.dat"}, {"test_data/ofdm_prach_demodulator_test_output141.dat"}},
  {{2048, {to_prach_format_type("A1"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input142.dat"}, {"test_data/ofdm_prach_demodulator_test_output142.dat"}},
  {{2048, {to_prach_format_type("A1"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input143.dat"}, {"test_data/ofdm_prach_demodulator_test_output143.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input144.dat"}, {"test_data/ofdm_prach_demodulator_test_output144.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input145.dat"}, {"test_data/ofdm_prach_demodulator_test_output145.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input146.dat"}, {"test_data/ofdm_prach_demodulator_test_output146.dat"}},
  {{2048, {to_prach_format_type("A2"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input147.dat"}, {"test_data/ofdm_prach_demodulator_test_output147.dat"}},
  {{2048, {to_prach_format_type("A2"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input148.dat"}, {"test_data/ofdm_prach_demodulator_test_output148.dat"}},
  {{2048, {to_prach_format_type("A2"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input149.dat"}, {"test_data/ofdm_prach_demodulator_test_output149.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input150.dat"}, {"test_data/ofdm_prach_demodulator_test_output150.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input151.dat"}, {"test_data/ofdm_prach_demodulator_test_output151.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input152.dat"}, {"test_data/ofdm_prach_demodulator_test_output152.dat"}},
  {{2048, {to_prach_format_type("A3"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input153.dat"}, {"test_data/ofdm_prach_demodulator_test_output153.dat"}},
  {{2048, {to_prach_format_type("A3"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input154.dat"}, {"test_data/ofdm_prach_demodulator_test_output154.dat"}},
  {{2048, {to_prach_format_type("A3"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input155.dat"}, {"test_data/ofdm_prach_demodulator_test_output155.dat"}},
  {{2048, {to_prach_format_type("B1"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input156.dat"}, {"test_data/ofdm_prach_demodulator_test_output156.dat"}},
  {{2048, {to_prach_format_type("B1"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input157.dat"}, {"test_data/ofdm_prach_demodulator_test_output157.dat"}},
  {{2048, {to_prach_format_type("B1"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input158.dat"}, {"test_data/ofdm_prach_demodulator_test_output158.dat"}},
  {{2048, {to_prach_format_type("B4"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input159.dat"}, {"test_data/ofdm_prach_demodulator_test_output159.dat"}},
  {{2048, {to_prach_format_type("B4"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input160.dat"}, {"test_data/ofdm_prach_demodulator_test_output160.dat"}},
  {{2048, {to_prach_format_type("B4"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input161.dat"}, {"test_data/ofdm_prach_demodulator_test_output161.dat"}},
  {{2048, {to_prach_format_type("C0"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input162.dat"}, {"test_data/ofdm_prach_demodulator_test_output162.dat"}},
  {{2048, {to_prach_format_type("C0"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input163.dat"}, {"test_data/ofdm_prach_demodulator_test_output163.dat"}},
  {{2048, {to_prach_format_type("C0"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input164.dat"}, {"test_data/ofdm_prach_demodulator_test_output164.dat"}},
  {{2048, {to_prach_format_type("C2"), 0, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input165.dat"}, {"test_data/ofdm_prach_demodulator_test_output165.dat"}},
  {{2048, {to_prach_format_type("C2"), 13, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input166.dat"}, {"test_data/ofdm_prach_demodulator_test_output166.dat"}},
  {{2048, {to_prach_format_type("C2"), 28, 52, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input167.dat"}, {"test_data/ofdm_prach_demodulator_test_output167.dat"}},
  {{4096, {to_prach_format_type("0"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input168.dat"}, {"test_data/ofdm_prach_demodulator_test_output168.dat"}},
  {{4096, {to_prach_format_type("0"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input169.dat"}, {"test_data/ofdm_prach_demodulator_test_output169.dat"}},
  {{4096, {to_prach_format_type("0"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input170.dat"}, {"test_data/ofdm_prach_demodulator_test_output170.dat"}},
  {{4096, {to_prach_format_type("1"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input171.dat"}, {"test_data/ofdm_prach_demodulator_test_output171.dat"}},
  {{4096, {to_prach_format_type("1"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input172.dat"}, {"test_data/ofdm_prach_demodulator_test_output172.dat"}},
  {{4096, {to_prach_format_type("1"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input173.dat"}, {"test_data/ofdm_prach_demodulator_test_output173.dat"}},
  {{4096, {to_prach_format_type("2"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input174.dat"}, {"test_data/ofdm_prach_demodulator_test_output174.dat"}},
  {{4096, {to_prach_format_type("2"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input175.dat"}, {"test_data/ofdm_prach_demodulator_test_output175.dat"}},
  {{4096, {to_prach_format_type("2"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input176.dat"}, {"test_data/ofdm_prach_demodulator_test_output176.dat"}},
  {{4096, {to_prach_format_type("3"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input177.dat"}, {"test_data/ofdm_prach_demodulator_test_output177.dat"}},
  {{4096, {to_prach_format_type("3"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input178.dat"}, {"test_data/ofdm_prach_demodulator_test_output178.dat"}},
  {{4096, {to_prach_format_type("3"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input179.dat"}, {"test_data/ofdm_prach_demodulator_test_output179.dat"}},
  {{4096, {to_prach_format_type("A1"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input180.dat"}, {"test_data/ofdm_prach_demodulator_test_output180.dat"}},
  {{4096, {to_prach_format_type("A1"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input181.dat"}, {"test_data/ofdm_prach_demodulator_test_output181.dat"}},
  {{4096, {to_prach_format_type("A1"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input182.dat"}, {"test_data/ofdm_prach_demodulator_test_output182.dat"}},
  {{4096, {to_prach_format_type("A1"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input183.dat"}, {"test_data/ofdm_prach_demodulator_test_output183.dat"}},
  {{4096, {to_prach_format_type("A1"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input184.dat"}, {"test_data/ofdm_prach_demodulator_test_output184.dat"}},
  {{4096, {to_prach_format_type("A1"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input185.dat"}, {"test_data/ofdm_prach_demodulator_test_output185.dat"}},
  {{4096, {to_prach_format_type("A2"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input186.dat"}, {"test_data/ofdm_prach_demodulator_test_output186.dat"}},
  {{4096, {to_prach_format_type("A2"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input187.dat"}, {"test_data/ofdm_prach_demodulator_test_output187.dat"}},
  {{4096, {to_prach_format_type("A2"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input188.dat"}, {"test_data/ofdm_prach_demodulator_test_output188.dat"}},
  {{4096, {to_prach_format_type("A2"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input189.dat"}, {"test_data/ofdm_prach_demodulator_test_output189.dat"}},
  {{4096, {to_prach_format_type("A2"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input190.dat"}, {"test_data/ofdm_prach_demodulator_test_output190.dat"}},
  {{4096, {to_prach_format_type("A2"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input191.dat"}, {"test_data/ofdm_prach_demodulator_test_output191.dat"}},
  {{4096, {to_prach_format_type("A3"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input192.dat"}, {"test_data/ofdm_prach_demodulator_test_output192.dat"}},
  {{4096, {to_prach_format_type("A3"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input193.dat"}, {"test_data/ofdm_prach_demodulator_test_output193.dat"}},
  {{4096, {to_prach_format_type("A3"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input194.dat"}, {"test_data/ofdm_prach_demodulator_test_output194.dat"}},
  {{4096, {to_prach_format_type("A3"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input195.dat"}, {"test_data/ofdm_prach_demodulator_test_output195.dat"}},
  {{4096, {to_prach_format_type("A3"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input196.dat"}, {"test_data/ofdm_prach_demodulator_test_output196.dat"}},
  {{4096, {to_prach_format_type("A3"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input197.dat"}, {"test_data/ofdm_prach_demodulator_test_output197.dat"}},
  {{4096, {to_prach_format_type("B1"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input198.dat"}, {"test_data/ofdm_prach_demodulator_test_output198.dat"}},
  {{4096, {to_prach_format_type("B1"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input199.dat"}, {"test_data/ofdm_prach_demodulator_test_output199.dat"}},
  {{4096, {to_prach_format_type("B1"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input200.dat"}, {"test_data/ofdm_prach_demodulator_test_output200.dat"}},
  {{4096, {to_prach_format_type("B4"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input201.dat"}, {"test_data/ofdm_prach_demodulator_test_output201.dat"}},
  {{4096, {to_prach_format_type("B4"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input202.dat"}, {"test_data/ofdm_prach_demodulator_test_output202.dat"}},
  {{4096, {to_prach_format_type("B4"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input203.dat"}, {"test_data/ofdm_prach_demodulator_test_output203.dat"}},
  {{4096, {to_prach_format_type("C0"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input204.dat"}, {"test_data/ofdm_prach_demodulator_test_output204.dat"}},
  {{4096, {to_prach_format_type("C0"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input205.dat"}, {"test_data/ofdm_prach_demodulator_test_output205.dat"}},
  {{4096, {to_prach_format_type("C0"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input206.dat"}, {"test_data/ofdm_prach_demodulator_test_output206.dat"}},
  {{4096, {to_prach_format_type("C2"), 0, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input207.dat"}, {"test_data/ofdm_prach_demodulator_test_output207.dat"}},
  {{4096, {to_prach_format_type("C2"), 13, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input208.dat"}, {"test_data/ofdm_prach_demodulator_test_output208.dat"}},
  {{4096, {to_prach_format_type("C2"), 28, 79, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input209.dat"}, {"test_data/ofdm_prach_demodulator_test_output209.dat"}},
  {{4096, {to_prach_format_type("0"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input210.dat"}, {"test_data/ofdm_prach_demodulator_test_output210.dat"}},
  {{4096, {to_prach_format_type("0"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input211.dat"}, {"test_data/ofdm_prach_demodulator_test_output211.dat"}},
  {{4096, {to_prach_format_type("0"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input212.dat"}, {"test_data/ofdm_prach_demodulator_test_output212.dat"}},
  {{4096, {to_prach_format_type("1"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input213.dat"}, {"test_data/ofdm_prach_demodulator_test_output213.dat"}},
  {{4096, {to_prach_format_type("1"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input214.dat"}, {"test_data/ofdm_prach_demodulator_test_output214.dat"}},
  {{4096, {to_prach_format_type("1"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input215.dat"}, {"test_data/ofdm_prach_demodulator_test_output215.dat"}},
  {{4096, {to_prach_format_type("2"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input216.dat"}, {"test_data/ofdm_prach_demodulator_test_output216.dat"}},
  {{4096, {to_prach_format_type("2"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input217.dat"}, {"test_data/ofdm_prach_demodulator_test_output217.dat"}},
  {{4096, {to_prach_format_type("2"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input218.dat"}, {"test_data/ofdm_prach_demodulator_test_output218.dat"}},
  {{4096, {to_prach_format_type("3"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input219.dat"}, {"test_data/ofdm_prach_demodulator_test_output219.dat"}},
  {{4096, {to_prach_format_type("3"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input220.dat"}, {"test_data/ofdm_prach_demodulator_test_output220.dat"}},
  {{4096, {to_prach_format_type("3"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input221.dat"}, {"test_data/ofdm_prach_demodulator_test_output221.dat"}},
  {{4096, {to_prach_format_type("A1"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input222.dat"}, {"test_data/ofdm_prach_demodulator_test_output222.dat"}},
  {{4096, {to_prach_format_type("A1"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input223.dat"}, {"test_data/ofdm_prach_demodulator_test_output223.dat"}},
  {{4096, {to_prach_format_type("A1"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input224.dat"}, {"test_data/ofdm_prach_demodulator_test_output224.dat"}},
  {{4096, {to_prach_format_type("A1"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input225.dat"}, {"test_data/ofdm_prach_demodulator_test_output225.dat"}},
  {{4096, {to_prach_format_type("A1"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input226.dat"}, {"test_data/ofdm_prach_demodulator_test_output226.dat"}},
  {{4096, {to_prach_format_type("A1"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input227.dat"}, {"test_data/ofdm_prach_demodulator_test_output227.dat"}},
  {{4096, {to_prach_format_type("A2"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input228.dat"}, {"test_data/ofdm_prach_demodulator_test_output228.dat"}},
  {{4096, {to_prach_format_type("A2"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input229.dat"}, {"test_data/ofdm_prach_demodulator_test_output229.dat"}},
  {{4096, {to_prach_format_type("A2"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input230.dat"}, {"test_data/ofdm_prach_demodulator_test_output230.dat"}},
  {{4096, {to_prach_format_type("A2"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input231.dat"}, {"test_data/ofdm_prach_demodulator_test_output231.dat"}},
  {{4096, {to_prach_format_type("A2"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input232.dat"}, {"test_data/ofdm_prach_demodulator_test_output232.dat"}},
  {{4096, {to_prach_format_type("A2"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input233.dat"}, {"test_data/ofdm_prach_demodulator_test_output233.dat"}},
  {{4096, {to_prach_format_type("A3"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input234.dat"}, {"test_data/ofdm_prach_demodulator_test_output234.dat"}},
  {{4096, {to_prach_format_type("A3"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input235.dat"}, {"test_data/ofdm_prach_demodulator_test_output235.dat"}},
  {{4096, {to_prach_format_type("A3"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input236.dat"}, {"test_data/ofdm_prach_demodulator_test_output236.dat"}},
  {{4096, {to_prach_format_type("A3"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input237.dat"}, {"test_data/ofdm_prach_demodulator_test_output237.dat"}},
  {{4096, {to_prach_format_type("A3"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input238.dat"}, {"test_data/ofdm_prach_demodulator_test_output238.dat"}},
  {{4096, {to_prach_format_type("A3"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input239.dat"}, {"test_data/ofdm_prach_demodulator_test_output239.dat"}},
  {{4096, {to_prach_format_type("B1"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input240.dat"}, {"test_data/ofdm_prach_demodulator_test_output240.dat"}},
  {{4096, {to_prach_format_type("B1"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input241.dat"}, {"test_data/ofdm_prach_demodulator_test_output241.dat"}},
  {{4096, {to_prach_format_type("B1"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input242.dat"}, {"test_data/ofdm_prach_demodulator_test_output242.dat"}},
  {{4096, {to_prach_format_type("B4"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input243.dat"}, {"test_data/ofdm_prach_demodulator_test_output243.dat"}},
  {{4096, {to_prach_format_type("B4"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input244.dat"}, {"test_data/ofdm_prach_demodulator_test_output244.dat"}},
  {{4096, {to_prach_format_type("B4"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input245.dat"}, {"test_data/ofdm_prach_demodulator_test_output245.dat"}},
  {{4096, {to_prach_format_type("C0"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input246.dat"}, {"test_data/ofdm_prach_demodulator_test_output246.dat"}},
  {{4096, {to_prach_format_type("C0"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input247.dat"}, {"test_data/ofdm_prach_demodulator_test_output247.dat"}},
  {{4096, {to_prach_format_type("C0"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input248.dat"}, {"test_data/ofdm_prach_demodulator_test_output248.dat"}},
  {{4096, {to_prach_format_type("C2"), 0, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input249.dat"}, {"test_data/ofdm_prach_demodulator_test_output249.dat"}},
  {{4096, {to_prach_format_type("C2"), 13, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input250.dat"}, {"test_data/ofdm_prach_demodulator_test_output250.dat"}},
  {{4096, {to_prach_format_type("C2"), 28, 106, subcarrier_spacing::kHz30}}, {"test_data/ofdm_prach_demodulator_test_input251.dat"}, {"test_data/ofdm_prach_demodulator_test_output251.dat"}},
    // clang-format on
};

} // namespace srsran
