/*
 *
 * Copyright 2021-2025 Software Radio Systems Limited
 *
 * By using this file, you agree to the terms and conditions set
 * forth in the LICENSE file which can be found at the top level of
 * the distribution.
 *
 */

/*******************************************************************************
 *
 *                     3GPP TS ASN1 XNAP v17.4.0 (2023-03)
 *
 ******************************************************************************/

#pragma once

#include "srsran/asn1/asn1_ap_utils.h"

namespace asn1 {
namespace xnap {

/*******************************************************************************
 *                             Constant Definitions
 ******************************************************************************/

#define ASN1_XNAP_ID_HO_PREP 0
#define ASN1_XNAP_ID_S_N_STATUS_TRANSFER 1
#define ASN1_XNAP_ID_HO_CANCEL 2
#define ASN1_XNAP_ID_RETRIEVE_UE_CONTEXT 3
#define ASN1_XNAP_ID_R_AN_PAGING 4
#define ASN1_XNAP_ID_XN_U_ADDRESS_IND 5
#define ASN1_XNAP_ID_U_E_CONTEXT_RELEASE 6
#define ASN1_XNAP_ID_S_NGRA_NNODE_ADDITION_PREP 7
#define ASN1_XNAP_ID_S_NGRA_NNODE_RECFG_COMPLETION 8
#define ASN1_XNAP_ID_M_NGRA_NNODEINITIATED_SN_GRA_NNODE_MOD_PREP 9
#define ASN1_XNAP_ID_S_NGRA_NNODEINITIATED_SN_GRA_NNODE_MOD_PREP 10
#define ASN1_XNAP_ID_M_NGRA_NNODEINITIATED_SN_GRA_NNODE_RELEASE 11
#define ASN1_XNAP_ID_S_NGRA_NNODEINITIATED_SN_GRA_NNODE_RELEASE 12
#define ASN1_XNAP_ID_S_NGRA_NNODE_COUNTER_CHECK 13
#define ASN1_XNAP_ID_S_NGRA_NNODE_CHANGE 14
#define ASN1_XNAP_ID_RRC_TRANSFER 15
#define ASN1_XNAP_ID_XN_REMOVAL 16
#define ASN1_XNAP_ID_XN_SETUP 17
#define ASN1_XNAP_ID_N_GRA_NNODE_CFG_UPD 18
#define ASN1_XNAP_ID_CELL_ACTIVATION 19
#define ASN1_XNAP_ID_RESET 20
#define ASN1_XNAP_ID_ERROR_IND 21
#define ASN1_XNAP_ID_PRIVATE_MSG 22
#define ASN1_XNAP_ID_NOTIF_CTRL 23
#define ASN1_XNAP_ID_ACTIVITY_NOTIF 24
#define ASN1_XNAP_ID_E_UTRA_NR_CELL_RES_COORDINATION 25
#define ASN1_XNAP_ID_SECONDARY_RAT_DATA_USAGE_REPORT 26
#define ASN1_XNAP_ID_DEACTIV_TRACE 27
#define ASN1_XNAP_ID_TRACE_START 28
#define ASN1_XNAP_ID_HO_SUCCESS 29
#define ASN1_XNAP_ID_CONDITIONAL_HO_CANCEL 30
#define ASN1_XNAP_ID_EARLY_STATUS_TRANSFER 31
#define ASN1_XNAP_ID_FAIL_IND 32
#define ASN1_XNAP_ID_HO_REPORT 33
#define ASN1_XNAP_ID_RES_STATUS_REPORT_INITIATION 34
#define ASN1_XNAP_ID_RES_STATUS_REPORT 35
#define ASN1_XNAP_ID_MOB_SETTINGS_CHANGE 36
#define ASN1_XNAP_ID_ACCESS_AND_MOB_IND 37
#define ASN1_XNAP_ID_CELL_TRAFFIC_TRACE 38
#define ASN1_XNAP_ID_RAN_MULTICAST_GROUP_PAGING 39
#define ASN1_XNAP_ID_SCG_FAIL_INFO_REPORT 40
#define ASN1_XNAP_ID_PROC_CODE41_NOT_TO_BE_USED 41
#define ASN1_XNAP_ID_SCG_FAIL_TRANSFER 42
#define ASN1_XNAP_ID_F1_C_TRAFFIC_TRANSFER 43
#define ASN1_XNAP_ID_I_AB_TRANSPORT_MIGRATION_MANAGEMENT 44
#define ASN1_XNAP_ID_I_AB_TRANSPORT_MIGRATION_MOD 45
#define ASN1_XNAP_ID_I_AB_RES_COORDINATION 46
#define ASN1_XNAP_ID_RETRIEVE_UE_CONTEXT_CONFIRM 47
#define ASN1_XNAP_ID_C_PC_CANCEL 48
#define ASN1_XNAP_ID_PARTIAL_UE_CONTEXT_TRANSFER 49
#define ASN1_XNAP_MAX_EARFCN 262143
#define ASN1_XNAP_MAXNOOF_ALLOWED_AREAS 16
#define ASN1_XNAP_MAXNOOF_AMF_REGIONS 16
#define ASN1_XNAP_MAXNOOF_AO_IS 64
#define ASN1_XNAP_MAXNOOF_BLUETOOTH_NAME 4
#define ASN1_XNAP_MAXNOOF_BPLMNS 12
#define ASN1_XNAP_MAXNOOF_CA_GS 12
#define ASN1_XNAP_MAXNOOF_CA_GSPER_PLMN 256
#define ASN1_XNAP_MAXNOOF_CELL_ID_FOR_MDT 32
#define ASN1_XNAP_MAXNOOF_CELLSIN_AO_I 256
#define ASN1_XNAP_MAXNOOF_CELLSIN_UE_HISTORY_INFO 16
#define ASN1_XNAP_MAXNOOF_CELLSIN_NG_RA_NNODE 16384
#define ASN1_XNAP_MAXNOOF_CELLSIN_RNA 32
#define ASN1_XNAP_MAXNOOF_CELLS_UE_MOVING_TRAJECTORY 16
#define ASN1_XNAP_MAXNOOF_DRBS 32
#define ASN1_XNAP_MAXNOOF_EUTRA_BANDS 16
#define ASN1_XNAP_MAXNOOF_EUTRA_BPLMNS 6
#define ASN1_XNAP_MAXNOOF_EPLMNS 15
#define ASN1_XNAP_MAXNOOF_EXT_SLICE_ITEMS 65535
#define ASN1_XNAP_MAXNOOF_EPLMN_SPLUS1 16
#define ASN1_XNAP_MAXNOOF_FORBIDDEN_TACS 4096
#define ASN1_XNAP_MAXNOOF_FREQFOR_MDT 8
#define ASN1_XNAP_MAXNOOF_MBSFN_EUTRA 8
#define ASN1_XNAP_MAXNOOF_MDT_PLMNS 16
#define ASN1_XNAP_MAXNOOF_MULTI_CONNECT_MINUS_ONE 3
#define ASN1_XNAP_MAXNOOF_NEIGHBOURS 1024
#define ASN1_XNAP_MAXNOOF_NEIGH_PCI_FOR_MDT 32
#define ASN1_XNAP_MAXNOOF_N_IDS 12
#define ASN1_XNAP_MAXNOOF_NR_CELL_BANDS 32
#define ASN1_XNAP_MAXNOOF_PLMNS 16
#define ASN1_XNAP_MAXNOOF_PDU_SESSIONS 256
#define ASN1_XNAP_MAXNOOF_PROTECTED_RES_PATTERNS 16
#define ASN1_XNAP_MAXNOOF_QOS_FLOWS 64
#define ASN1_XNAP_MAXNOOF_QOS_PARA_SETS 8
#define ASN1_XNAP_MAXNOOF_RAN_AREA_CODES 32
#define ASN1_XNAP_MAXNOOF_RAN_AREASIN_RNA 16
#define ASN1_XNAP_MAXNOOF_RAN_NODESIN_AO_I 64
#define ASN1_XNAP_MAXNOOF_SCELL_GROUPS 3
#define ASN1_XNAP_MAXNOOF_SCELL_GROUPSPLUS1 4
#define ASN1_XNAP_MAXNOOF_SENSOR_NAME 3
#define ASN1_XNAP_MAXNOOF_SLICE_ITEMS 1024
#define ASN1_XNAP_MAXNOOF_SN_PN_IDS 12
#define ASN1_XNAP_MAXNOOFSUPPORTED_PLMNS 12
#define ASN1_XNAP_MAXNOOFSUPPORTED_TACS 256
#define ASN1_XNAP_MAXNOOF_TA_FOR_MDT 8
#define ASN1_XNAP_MAXNOOF_TAI 16
#define ASN1_XNAP_MAXNOOF_TAI_SIN_AO_I 16
#define ASN1_XNAP_MAXNOOFTIMEPERIODS 2
#define ASN1_XNAP_MAXNOOF_TNL_ASSOCS 32
#define ASN1_XNAP_MAXNOOF_UE_CONTEXTS 8192
#define ASN1_XNAP_MAX_NR_ARFCN 3279165
#define ASN1_XNAP_MAX_NR_OF_ERRORS 256
#define ASN1_XNAP_MAXNOOFSLOTS 5120
#define ASN1_XNAP_MAXNOOF_EXT_TLAS 16
#define ASN1_XNAP_MAXNOOF_GTP_TLAS 16
#define ASN1_XNAP_MAXNOOF_CH_OCELLS 8
#define ASN1_XNAP_MAXNOOF_PC5_QOS_FLOWS 2064
#define ASN1_XNAP_MAXNOOF_SSB_AREAS 64
#define ASN1_XNAP_MAXNOOF_RACH_REPORTS 64
#define ASN1_XNAP_MAXNOOF_NR_SC_SS 5
#define ASN1_XNAP_MAXNOOF_PHYS_RES_BLOCKS 275
#define ASN1_XNAP_MAXNOOF_ADD_PDCP_DUPL_TNL 2
#define ASN1_XNAP_MAXNOOF_RLC_DUPLSTATE 3
#define ASN1_XNAP_MAXNOOF_WLAN_NAME 4
#define ASN1_XNAP_MAXNOOF_NON_ANCHOR_CARRIER_FREQ_CFG 15
#define ASN1_XNAP_MAXNOOF_DATA_FORWARDING_TUNNELTO_E_UTRAN 256
#define ASN1_XNAP_MAXNOOF_MBSFS_AS 256
#define ASN1_XNAP_MAXNOOF_UE_ID_INDICESFOR_MBS_PAGING 4096
#define ASN1_XNAP_MAXNOOF_MBS_QOS_FLOWS 64
#define ASN1_XNAP_MAXNOOF_M_RBS 32
#define ASN1_XNAP_MAXNOOF_CELLSFOR_MBS 8192
#define ASN1_XNAP_MAXNOOF_MBS_SERVICE_AREA_INFO 256
#define ASN1_XNAP_MAXNOOF_TAI_FOR_MBS 1024
#define ASN1_XNAP_MAXNOOF_ASSOCIATED_MBS_SESSIONS 32
#define ASN1_XNAP_MAXNOOF_MBS_SESSIONS 256
#define ASN1_XNAP_MAXNOOF_SUCCESSFUL_HO_REPORTS 64
#define ASN1_XNAP_MAXNOOF_P_SCELLS_PER_SN 8
#define ASN1_XNAP_MAXNOOF_NR_U_CH_IDS 16
#define ASN1_XNAP_MAXNOOF_CELLSIN_CHO 8
#define ASN1_XNAP_MAXNOOF_CH_OEXECUTIONCOND 2
#define ASN1_XNAP_MAXNOOF_SERVED_CELLS_IAB 512
#define ASN1_XNAP_MAXNOOF_SERVING_CELLS 32
#define ASN1_XNAP_MAXNOOF_BH_INFO 1024
#define ASN1_XNAP_MAXNOOF_TRAFFIC_IDX_ENTRIES 1024
#define ASN1_XNAP_MAXNOOF_TLAS_IAB 1024
#define ASN1_XNAP_MAXNOOF_BAP_CTRL_PDU_RLC_C_HS 2
#define ASN1_XNAP_MAXNOOF_IABSTC_INFO 45
#define ASN1_XNAP_MAXNOOF_SYMBOLS 14
#define ASN1_XNAP_MAXNOOF_DU_F_SLOTS 320
#define ASN1_XNAP_MAXNOOF_HS_NAS_LOTS 5120
#define ASN1_XNAP_MAXNOOF_R_BSETS_PER_CELL 8
#define ASN1_XNAP_MAXNOOF_R_BSETS_PER_CELL1 7
#define ASN1_XNAP_MAXNOOF_CHILD_IAB_NODES 1024
#define ASN1_XNAP_MAXNOOF_PSCELL_CANDIDATES 8
#define ASN1_XNAP_MAXNOOF_TARGET_SN_S 8
#define ASN1_XNAP_MAXNOOF_UE_APP_LAYER_MEAS 16
#define ASN1_XNAP_MAXNOOF_SNSSAI_FOR_QMC 16
#define ASN1_XNAP_MAXNOOF_CELL_ID_FOR_QMC 32
#define ASN1_XNAP_MAXNOOF_PLMN_FOR_QMC 16
#define ASN1_XNAP_MAXNOOF_TA_FOR_QMC 8
#define ASN1_XNAP_MAXNOOF_MTC_ITEM_S 16
#define ASN1_XNAP_MAXNOOF_CSI_R_SCFGS 96
#define ASN1_XNAP_MAXNOOF_CSI_R_SNEIGHBOUR_CELLS 16
#define ASN1_XNAP_MAXNOOF_CSI_R_SNEIGHBOUR_CELLS_IN_MTC 16
#define ASN1_XNAP_MAXNOOF_NEIGHBOUR_NG_RAN_NODES 256
#define ASN1_XNAP_MAXNOOF_SRBS 5
#define ASN1_XNAP_MAXNOOF_SMBR 8
#define ASN1_XNAP_MAXNOOF_NSA_GS 256
#define ASN1_XNAP_MAXNOOF_TARGET_SN_S_MINUS_ONE 7
#define ASN1_XNAP_MAXNOOF_THRESS_FOR_EXCESS_PACKET_DELAY 255
#define ASN1_XNAP_ID_ACTIV_SERVED_CELLS 0
#define ASN1_XNAP_ID_ACTIVATION_ID_FOR_CELL_ACTIVATION 1
#define ASN1_XNAP_ID_ADMITTED_SPLIT_SRB 2
#define ASN1_XNAP_ID_ADMITTED_SPLIT_SRB_RELEASE 3
#define ASN1_XNAP_ID_AMF_REGION_INFO 4
#define ASN1_XNAP_ID_ASSIST_DATA_FOR_RAN_PAGING 5
#define ASN1_XNAP_ID_BEARERS_SUBJECT_TO_COUNTER_CHECK 6
#define ASN1_XNAP_ID_CAUSE 7
#define ASN1_XNAP_ID_CELL_ASSIST_INFO_NR 8
#define ASN1_XNAP_ID_CFG_UPD_INIT_NODE_CHOICE 9
#define ASN1_XNAP_ID_CRIT_DIAGNOSTICS 10
#define ASN1_XNAP_ID_XN_U_ADDRESS_INFOPER_PDU_SESSION_LIST 11
#define ASN1_XNAP_ID_DRBS_SUBJECT_TO_STATUS_TRANSFER_LIST 12
#define ASN1_XNAP_ID_EXPECTED_UE_BEHAVIOUR 13
#define ASN1_XNAP_ID_GLOBAL_NG_RAN_NODE_ID 14
#define ASN1_XNAP_ID_GUAMI 15
#define ASN1_XNAP_ID_IDX_TO_RAT_FREQU_SEL_PRIO 16
#define ASN1_XNAP_ID_INIT_NODE_TYPE_RES_COORD_REQUEST 17
#define ASN1_XNAP_ID_LIST_OF_SERVED_CELLS_E_UTRA 18
#define ASN1_XNAP_ID_LIST_OF_SERVED_CELLS_NR 19
#define ASN1_XNAP_ID_LOCATION_REPORT_INFO 20
#define ASN1_XNAP_ID_MAC_I 21
#define ASN1_XNAP_ID_MASKED_IMEISV 22
#define ASN1_XNAP_ID_M_NG_RA_NNODE_UE_XN_AP_ID 23
#define ASN1_XNAP_ID_MN_TO_SN_CONTAINER 24
#define ASN1_XNAP_ID_MOB_RESTRICT_LIST 25
#define ASN1_XNAP_ID_NEW_NG_RAN_CELL_ID 26
#define ASN1_XNAP_ID_NEW_NG_RA_NNODE_UE_XN_AP_ID 27
#define ASN1_XNAP_ID_UE_REPORT_RRC_TRANSFER 28
#define ASN1_XNAP_ID_OLD_NG_RA_NNODE_UE_XN_AP_ID 29
#define ASN1_XNAP_ID_OLDTO_NEW_NG_RA_NNODE_RESUME_CONTAINER 30
#define ASN1_XNAP_ID_PAGING_DRX 31
#define ASN1_XNAP_ID_PCELL_ID 32
#define ASN1_XNAP_ID_PDCP_CHANGE_IND 33
#define ASN1_XNAP_ID_PDU_SESSION_ADMITTED_ADDED_ADD_REQ_ACK 34
#define ASN1_XNAP_ID_PDU_SESSION_ADMITTED_MOD_SN_MOD_CONFIRM 35
#define ASN1_XNAP_ID_PDU_SESSION_ADMITTED_SN_MOD_RESP 36
#define ASN1_XNAP_ID_PDU_SESSION_NOT_ADMITTED_ADD_REQ_ACK 37
#define ASN1_XNAP_ID_PDU_SESSION_NOT_ADMITTED_SN_MOD_RESP 38
#define ASN1_XNAP_ID_PDU_SESSION_RELEASED_LIST_REL_CONF 39
#define ASN1_XNAP_ID_PDU_SESSION_RELEASED_SN_MOD_CONFIRM 40
#define ASN1_XNAP_ID_PDU_SESSION_RES_ACTIVITY_NOTIFY_LIST 41
#define ASN1_XNAP_ID_PDU_SESSION_RES_ADMITTED_LIST 42
#define ASN1_XNAP_ID_PDU_SESSION_RES_NOT_ADMITTED_LIST 43
#define ASN1_XNAP_ID_PDU_SESSION_RES_NOTIFY_LIST 44
#define ASN1_XNAP_ID_PDU_SESSION_SN_CHANGE_CONFIRM_LIST 45
#define ASN1_XNAP_ID_PDU_SESSION_SN_CHANGE_REQUIRED_LIST 46
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_ADDED_ADD_REQ 47
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_MODIFIED_SN_MOD_REQUIRED 48
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_RELEASED_LIST_REL_RQD 49
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_RELEASED_REL_REQ 50
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_RELEASED_SN_MOD_REQUIRED 51
#define ASN1_XNAP_ID_RAN_PAGING_AREA 52
#define ASN1_XNAP_ID_PAGING_PRIO 53
#define ASN1_XNAP_ID_REQUESTED_SPLIT_SRB 54
#define ASN1_XNAP_ID_REQUESTED_SPLIT_SRB_RELEASE 55
#define ASN1_XNAP_ID_RESET_REQUEST_TYPE_INFO 56
#define ASN1_XNAP_ID_RESET_RESP_TYPE_INFO 57
#define ASN1_XNAP_ID_RESPONDING_NODE_TYPE_CFG_UPD_ACK 58
#define ASN1_XNAP_ID_RESPONDING_NODE_TYPE_RES_COORD_RESP 59
#define ASN1_XNAP_ID_RESP_INFO_RECONF_COMPL 60
#define ASN1_XNAP_ID_RRC_CFG_IND 61
#define ASN1_XNAP_ID_RRC_RESUME_CAUSE 62
#define ASN1_XNAP_ID_SCG_CFG_QUERY 63
#define ASN1_XNAP_ID_SEL_PLMN 64
#define ASN1_XNAP_ID_SERVED_CELLS_TO_ACTIV 65
#define ASN1_XNAP_ID_SERVED_CELLS_TO_UPD_E_UTRA 66
#define ASN1_XNAP_ID_SERVED_CELLS_TO_UPD_INIT_NODE_CHOICE 67
#define ASN1_XNAP_ID_SERVED_CELLS_TO_UPD_NR 68
#define ASN1_XNAP_ID_S_NG_RA_NNODE_SECURITY_KEY 69
#define ASN1_XNAP_ID_S_NG_RA_NNODE_UE_AMBR 70
#define ASN1_XNAP_ID_S_NG_RA_NNODE_UE_XN_AP_ID 71
#define ASN1_XNAP_ID_SN_TO_MN_CONTAINER 72
#define ASN1_XNAP_ID_SOURCE_NG_RA_NNODE_UE_XN_AP_ID 73
#define ASN1_XNAP_ID_SPLIT_SRB_RRC_TRANSFER 74
#define ASN1_XNAP_ID_TAI_SUPPORT_LIST 75
#define ASN1_XNAP_ID_TIME_TO_WAIT 76
#define ASN1_XNAP_ID_TARGET2_SOURCE_NG_RA_NNODE_TRANSP_CONTAINER 77
#define ASN1_XNAP_ID_TARGET_CELL_GLOBAL_ID 78
#define ASN1_XNAP_ID_TARGET_NG_RA_NNODE_UE_XN_AP_ID 79
#define ASN1_XNAP_ID_TARGET_S_NG_RA_NNODE_ID 80
#define ASN1_XNAP_ID_TRACE_ACTIVATION 81
#define ASN1_XNAP_ID_UE_CONTEXT_ID 82
#define ASN1_XNAP_ID_UE_CONTEXT_INFO_HO_REQUEST 83
#define ASN1_XNAP_ID_UE_CONTEXT_INFO_RETR_UE_CTXT_RESP 84
#define ASN1_XNAP_ID_UE_CONTEXT_INFO_SN_MOD_REQUEST 85
#define ASN1_XNAP_ID_UE_CONTEXT_KEPT_IND 86
#define ASN1_XNAP_ID_UE_CONTEXT_REF_AT_SN_HO_REQUEST 87
#define ASN1_XNAP_ID_UE_HISTORY_INFO 88
#define ASN1_XNAP_ID_UE_ID_IDX_VALUE 89
#define ASN1_XNAP_ID_UE_RAN_PAGING_ID 90
#define ASN1_XNAP_ID_UE_SECURITY_CAP 91
#define ASN1_XNAP_ID_USER_PLANE_TRAFFIC_ACTIVITY_REPORT 92
#define ASN1_XNAP_ID_XN_REMOVAL_THRES 93
#define ASN1_XNAP_ID_DESIRED_ACT_NOTIF_LEVEL 94
#define ASN1_XNAP_ID_AVAILABLE_DRB_IDS 95
#define ASN1_XNAP_ID_ADD_DRB_IDS 96
#define ASN1_XNAP_ID_SPARE_DRB_IDS 97
#define ASN1_XNAP_ID_REQUIRED_NOF_DRB_IDS 98
#define ASN1_XNAP_ID_TNL_A_TO_ADD_LIST 99
#define ASN1_XNAP_ID_TNL_A_TO_UPD_LIST 100
#define ASN1_XNAP_ID_TNL_A_TO_REM_LIST 101
#define ASN1_XNAP_ID_TNL_A_SETUP_LIST 102
#define ASN1_XNAP_ID_TNL_A_FAILED_TO_SETUP_LIST 103
#define ASN1_XNAP_ID_PDU_SESSION_TO_BE_RELEASED_REL_REQ_ACK 104
#define ASN1_XNAP_ID_S_NG_RA_NNODE_MAX_IP_DATA_RATE_UL 105
#define ASN1_XNAP_ID_PDU_SESSION_RES_SECONDARY_RAT_USAGE_LIST 107
#define ASN1_XNAP_ID_ADD_UL_NG_U_TNL_AT_UP_F_LIST 108
#define ASN1_XNAP_ID_SECONDARYDATA_FORWARDING_INFO_FROM_TARGET_LIST 109
#define ASN1_XNAP_ID_LOCATION_INFO_SNR_EPORTING 110
#define ASN1_XNAP_ID_LOCATION_INFO_SN 111
#define ASN1_XNAP_ID_LAST_E_UTRAN_PLMN_ID 112
#define ASN1_XNAP_ID_S_NG_RA_NNODE_MAX_IP_DATA_RATE_DL 113
#define ASN1_XNAP_ID_MAX_IP_RATE_DL 114
#define ASN1_XNAP_ID_SECURITY_RESULT 115
#define ASN1_XNAP_ID_S_NSSAI 116
#define ASN1_XNAP_ID_MR_DC_RES_COORDINATION_INFO 117
#define ASN1_XNAP_ID_AMF_REGION_INFO_TO_ADD 118
#define ASN1_XNAP_ID_AMF_REGION_INFO_TO_DELETE 119
#define ASN1_XNAP_ID_OLD_QOS_FLOW_MAP_UL_ENDMARKEREXPECTED 120
#define ASN1_XNAP_ID_RAN_PAGING_FAIL 121
#define ASN1_XNAP_ID_UE_RADIO_CAP_FOR_PAGING 122
#define ASN1_XNAP_ID_PDU_SESSION_DATA_FORWARDING_SN_MOD_RESP 123
#define ASN1_XNAP_ID_DRBS_NOT_ADMITTED_SETUP_MODIFY_LIST 124
#define ASN1_XNAP_ID_SECONDARY_MN_XN_U_TNL_INFOAT_M 125
#define ASN1_XNAP_ID_NE_DC_TDM_PATTERN 126
#define ASN1_XNAP_ID_PDU_SESSION_COMMON_NETWORK_INSTANCE 127
#define ASN1_XNAP_ID_BPLMN_ID_INFO_EUTRA 128
#define ASN1_XNAP_ID_BPLMN_ID_INFO_NR 129
#define ASN1_XNAP_ID_INTERFACE_INSTANCE_IND 130
#define ASN1_XNAP_ID_S_NG_RA_NNODE_ADDITION_TRIGGER_IND 131
#define ASN1_XNAP_ID_DEFAULT_DRB_ALLOWED 132
#define ASN1_XNAP_ID_DRB_IDS_TAKENINTOUSE 133
#define ASN1_XNAP_ID_SPLIT_SESSION_IND 134
#define ASN1_XNAP_ID_CN_TYPE_RESTRICTS_FOR_EQUIVALENT 135
#define ASN1_XNAP_ID_CN_TYPE_RESTRICTS_FOR_SERVING 136
#define ASN1_XNAP_ID_DRBS_TRANSFERRED_TO_MN 137
#define ASN1_XNAP_ID_UL_FORWARDING_PROPOSAL 138
#define ASN1_XNAP_ID_ENDPOINT_IP_ADDRESS_AND_PORT 139
#define ASN1_XNAP_ID_INTENDED_TDD_DL_UL_CFG_NR 140
#define ASN1_XNAP_ID_TNL_CFG_INFO 141
#define ASN1_XNAP_ID_PARTIAL_LIST_IND_NR 142
#define ASN1_XNAP_ID_MSG_OVERSIZE_NOTIF 143
#define ASN1_XNAP_ID_CELL_AND_CAPACITY_ASSIST_INFO_NR 144
#define ASN1_XNAP_ID_NG_RAN_TRACE_ID 145
#define ASN1_XNAP_ID_NON_GBR_RES_OFFERED 146
#define ASN1_XNAP_ID_FAST_MCG_RECOVERY_RRC_TRANSFER_SN_TO_MN 147
#define ASN1_XNAP_ID_REQUESTED_FAST_MCG_RECOVERY_VIA_SRB3 148
#define ASN1_XNAP_ID_AVAILABLE_FAST_MCG_RECOVERY_VIA_SRB3 149
#define ASN1_XNAP_ID_REQUESTED_FAST_MCG_RECOVERY_VIA_SRB3_RELEASE 150
#define ASN1_XNAP_ID_RELEASE_FAST_MCG_RECOVERY_VIA_SRB3 151
#define ASN1_XNAP_ID_FAST_MCG_RECOVERY_RRC_TRANSFER_MN_TO_SN 152
#define ASN1_XNAP_ID_EXTENDED_RAT_RESTRICT_INFO 153
#define ASN1_XNAP_ID_QOS_MONITORING_REQUEST 154
#define ASN1_XNAP_ID_FIVE_GC_MOB_RESTRICT_LIST_CONTAINER 155
#define ASN1_XNAP_ID_PARTIAL_LIST_IND_EUTRA 156
#define ASN1_XNAP_ID_CELL_AND_CAPACITY_ASSIST_INFO_EUTRA 157
#define ASN1_XNAP_ID_CH_OINFO_REQ 158
#define ASN1_XNAP_ID_CH_OINFO_ACK 159
#define ASN1_XNAP_ID_TARGET_CELLS_TO_CANCEL 160
#define ASN1_XNAP_ID_REQUESTED_TARGET_CELL_GLOBAL_ID 161
#define ASN1_XNAP_ID_PROC_STAGE 162
#define ASN1_XNAP_ID_DAPS_REQUEST_INFO 163
#define ASN1_XNAP_ID_DAPS_RESP_INFO_LIST 164
#define ASN1_XNAP_ID_CHO_MRDC_IND 165
#define ASN1_XNAP_ID_OFFSET_OF_NBIOT_CH_NUM_TO_DL_EARFCN 166
#define ASN1_XNAP_ID_OFFSET_OF_NBIOT_CH_NUM_TO_UL_EARFCN 167
#define ASN1_XNAP_ID_NB_IOT_UL_DL_ALIGN_OFFSET 168
#define ASN1_XNAP_ID_LTEV2X_SERVICES_AUTHORIZED 169
#define ASN1_XNAP_ID_NR_V2X_SERVICES_AUTHORIZED 170
#define ASN1_XNAP_ID_LTE_UE_SIDELINK_AGGR_MAX_BIT_RATE 171
#define ASN1_XNAP_ID_NR_UE_SIDELINK_AGGR_MAX_BIT_RATE 172
#define ASN1_XNAP_ID_PC5_QOS_PARAMS 173
#define ASN1_XNAP_ID_ALT_QOS_PARA_SET_LIST 174
#define ASN1_XNAP_ID_CURRENT_QOS_PARA_SET_IDX 175
#define ASN1_XNAP_ID_MOB_INFO 176
#define ASN1_XNAP_ID_INIT_CONDITION_FAIL_IND 177
#define ASN1_XNAP_ID_UE_HISTORY_INFO_FROM_THE_UE 178
#define ASN1_XNAP_ID_HO_REPORT_TYPE 179
#define ASN1_XNAP_ID_HO_CAUSE 180
#define ASN1_XNAP_ID_SOURCE_CELL_CGI 181
#define ASN1_XNAP_ID_TARGET_CELL_CGI 182
#define ASN1_XNAP_ID_RE_ESTABLISHMENT_CELL_CGI 183
#define ASN1_XNAP_ID_TARGET_CELLIN_EUTRAN 184
#define ASN1_XNAP_ID_SOURCE_CELL_C_RNTI 185
#define ASN1_XNAP_ID_UE_RLF_REPORT_CONTAINER 186
#define ASN1_XNAP_ID_NGRAN_NODE1_MEAS_ID 187
#define ASN1_XNAP_ID_NGRAN_NODE2_MEAS_ID 188
#define ASN1_XNAP_ID_REGIST_REQUEST 189
#define ASN1_XNAP_ID_REPORT_CHARACTERISTICS 190
#define ASN1_XNAP_ID_CELL_TO_REPORT 191
#define ASN1_XNAP_ID_REPORT_PERIODICITY 192
#define ASN1_XNAP_ID_CELL_MEAS_RESULT 193
#define ASN1_XNAP_ID_NG_RA_NNODE1_CELL_ID 194
#define ASN1_XNAP_ID_NG_RA_NNODE2_CELL_ID 195
#define ASN1_XNAP_ID_NG_RA_NNODE1_MOB_PARAMS 196
#define ASN1_XNAP_ID_NG_RA_NNODE2_PROPOSED_MOB_PARAMS 197
#define ASN1_XNAP_ID_MOB_PARAMS_MOD_RANGE 198
#define ASN1_XNAP_ID_TDD_UL_DL_CFG_COMMON_NR 199
#define ASN1_XNAP_ID_CARRIER_LIST 200
#define ASN1_XNAP_ID_UL_CARRIER_LIST 201
#define ASN1_XNAP_ID_FREQ_SHIFT7P5KHZ 202
#define ASN1_XNAP_ID_SSB_POSITIONS_IN_BURST 203
#define ASN1_XNAP_ID_NR_CELL_PRACH_CFG 204
#define ASN1_XNAP_ID_RACH_REPORT_INFO 205
#define ASN1_XNAP_ID_IAB_NODE_IND 206
#define ASN1_XNAP_ID_REDUNDANT_UL_NG_U_TNL_AT_UP_F 207
#define ASN1_XNAP_ID_CN_PACKET_DELAY_BUDGET_DL 208
#define ASN1_XNAP_ID_CN_PACKET_DELAY_BUDGET_UL 209
#define ASN1_XNAP_ID_ADD_REDUNDANT_UL_NG_U_TNL_AT_UP_F_LIST 210
#define ASN1_XNAP_ID_REDUNDANT_COMMON_NETWORK_INSTANCE 211
#define ASN1_XNAP_ID_TSC_TRAFFIC_CHARACTERISTICS 212
#define ASN1_XNAP_ID_REDUNDANT_QOS_FLOW_IND 213
#define ASN1_XNAP_ID_REDUNDANT_DL_NG_U_TNL_AT_NG_RAN 214
#define ASN1_XNAP_ID_EXTENDED_PACKET_DELAY_BUDGET 215
#define ASN1_XNAP_ID_ADD_PDCP_DUPL_TNL_LIST 216
#define ASN1_XNAP_ID_REDUNDANT_PDU_SESSION_INFO 217
#define ASN1_XNAP_ID_USED_R_SN_INFO 218
#define ASN1_XNAP_ID_RLC_DUPL_INFO 219
#define ASN1_XNAP_ID_NPN_BROADCAST_INFO 220
#define ASN1_XNAP_ID_NPN_PAGING_ASSIST_INFO 221
#define ASN1_XNAP_ID_NPN_MOB_INFO 222
#define ASN1_XNAP_ID_NPN_SUPPORT 223
#define ASN1_XNAP_ID_MDT_CFG 224
#define ASN1_XNAP_ID_MDT_PLMN_LIST 225
#define ASN1_XNAP_ID_TRACE_COLLECTION_ENTITY_URI 226
#define ASN1_XNAP_ID_UE_RADIO_CAP_ID 227
#define ASN1_XNAP_ID_CSI_RS_TX_IND 228
#define ASN1_XNAP_ID_SN_TRIGGERED 229
#define ASN1_XNAP_ID_DL_CARRIER_LIST 230
#define ASN1_XNAP_ID_EXTENDED_TAI_SLICE_SUPPORT_LIST 231
#define ASN1_XNAP_ID_CELL_ASSIST_INFO_EUTRA 232
#define ASN1_XNAP_ID_CFG_TAC_IND 233
#define ASN1_XNAP_ID_SECONDARY_SN_UL_PDCP_UP_TNL_INFO 234
#define ASN1_XNAP_ID_PDCP_DUPL_CFG 235
#define ASN1_XNAP_ID_DUPL_ACTIVATION 236
#define ASN1_XNAP_ID_NPRACH_CFG 237
#define ASN1_XNAP_ID_QOS_MONITORING_REPORT_FREQ 238
#define ASN1_XNAP_ID_QOS_FLOWS_MAPPEDTO_DRB_SETUP_RESP_M_NTERMINATED 239
#define ASN1_XNAP_ID_DL_SCHED_PDCCH_CCE_USAGE 240
#define ASN1_XNAP_ID_UL_SCHED_PDCCH_CCE_USAGE 241
#define ASN1_XNAP_ID_SFN_OFFSET 242
#define ASN1_XNAP_ID_QOS_MONITORING_DISABLED 243
#define ASN1_XNAP_ID_EXTENDED_UE_ID_IDX_VALUE 244
#define ASN1_XNAP_ID_EUTRA_PAGINGE_DRX_INFO 245
#define ASN1_XNAP_ID_CHO_MRDC_EARLY_DATA_FORWARDING 246
#define ASN1_XNAP_ID_SCG_IND 247
#define ASN1_XNAP_ID_UE_SPECIFIC_DRX 248
#define ASN1_XNAP_ID_PDU_SESSION_EXPECTED_UE_ACTIVITY_BEHAVIOUR 249
#define ASN1_XNAP_ID_QOS_MAP_INFO 250
#define ASN1_XNAP_ID_ADDITION_LOCATION_INFO 251
#define ASN1_XNAP_ID_DATA_FORWARDING_INFO_FROM_TARGET_E_UTRAN_NODE 252
#define ASN1_XNAP_ID_DIRECT_FORWARDING_PATH_AVAILABILITY 253
#define ASN1_XNAP_ID_SOURCE_NG_RAN_NODE_ID 254
#define ASN1_XNAP_ID_SOURCE_DL_FORWARDING_IP_ADDRESS 255
#define ASN1_XNAP_ID_SOURCE_NODE_DL_FORWARDING_IP_ADDRESS 256
#define ASN1_XNAP_ID_EXTENDED_REPORT_INTERV_MDT 257
#define ASN1_XNAP_ID_SECURITY_IND 258
#define ASN1_XNAP_ID_RRC_CONN_REESTAB_IND 259
#define ASN1_XNAP_ID_TARGET_NODE_ID 260
#define ASN1_XNAP_ID_MANAGEMENT_BASED_MDT_PLMN_LIST 261
#define ASN1_XNAP_ID_PRIVACY_IND 262
#define ASN1_XNAP_ID_TRACE_COLLECTION_ENTITY_IP_ADDRESS 263
#define ASN1_XNAP_ID_M4_REPORT_AMOUNT 264
#define ASN1_XNAP_ID_M5_REPORT_AMOUNT 265
#define ASN1_XNAP_ID_M6_REPORT_AMOUNT 266
#define ASN1_XNAP_ID_M7_REPORT_AMOUNT 267
#define ASN1_XNAP_ID_BEAM_MEAS_IND_M1 268
#define ASN1_XNAP_ID_MBS_SESSION_ID 269
#define ASN1_XNAP_ID_UE_ID_IDX_LIST_MBS_GROUP_PAGING 270
#define ASN1_XNAP_ID_MULTICAST_RAN_PAGING_AREA 271
#define ASN1_XNAP_ID_SUPPORTED_MBS_FSA_ID_LIST 272
#define ASN1_XNAP_ID_MBS_SESSION_INFO_LIST 273
#define ASN1_XNAP_ID_MBS_SESSION_INFO_RESP_LIST 274
#define ASN1_XNAP_ID_MBS_SESSION_ASSOCIATED_INFO 275
#define ASN1_XNAP_ID_SUCCESSFUL_HO_REPORT_INFO 276
#define ASN1_XNAP_ID_SLICE_RR_STATUS_LIST 277
#define ASN1_XNAP_ID_COMPOSITE_AVAILABLE_CAPACITY_SUPPLEMENTARY_UL 278
#define ASN1_XNAP_ID_SCG_UE_HISTORY_INFO 279
#define ASN1_XNAP_ID_SSB_OFFSETS_LIST 280
#define ASN1_XNAP_ID_NG_RA_NNODE2_SSB_OFFSET_MOD_RANGE 281
#define ASN1_XNAP_ID_COVERAGE_MOD_LIST 282
#define ASN1_XNAP_ID_NR_U_CH_LIST 283
#define ASN1_XNAP_ID_SOURCE_PSCELL_CGI 284
#define ASN1_XNAP_ID_FAILED_PSCELL_CGI 285
#define ASN1_XNAP_ID_SCG_FAIL_REPORT_CONTAINER 286
#define ASN1_XNAP_ID_SN_MOB_INFO 287
#define ASN1_XNAP_ID_SOURCE_PSCELL_ID 288
#define ASN1_XNAP_ID_SUITABLE_PSCELL_CGI 289
#define ASN1_XNAP_ID_PSCELL_CHANGE_HISTORY 290
#define ASN1_XNAP_ID_CHO_CFG 291
#define ASN1_XNAP_ID_NR_U_CH_INFO_LIST 292
#define ASN1_XNAP_ID_PSCELL_HISTORY_INFO_RETRIEVE 293
#define ASN1_XNAP_ID_NG_RA_NNODE2_SSB_OFFSETS_MOD_RANGE 294
#define ASN1_XNAP_ID_MIMO_PRB_USAGE_INFO 295
#define ASN1_XNAP_ID_F1_C_TRAFFIC_CONTAINER 296
#define ASN1_XNAP_ID_IAB_MT_CELL_LIST 297
#define ASN1_XNAP_ID_NO_PDU_SESSION_IND 298
#define ASN1_XNAP_ID_IAB_TNL_ADDRESS_REQUEST 299
#define ASN1_XNAP_ID_IAB_TNL_ADDRESS_RESP 300
#define ASN1_XNAP_ID_TRAFFIC_TO_BE_ADDED_LIST 301
#define ASN1_XNAP_ID_TRAFFIC_TO_BE_MODIFIED_LIST 302
#define ASN1_XNAP_ID_TRAFFIC_TO_BE_RELEASE_INFO 303
#define ASN1_XNAP_ID_TRAFFIC_ADDED_LIST 304
#define ASN1_XNAP_ID_TRAFFIC_MODIFIED_LIST 305
#define ASN1_XNAP_ID_TRAFFIC_NOT_ADDED_LIST 306
#define ASN1_XNAP_ID_TRAFFIC_NOT_MODIFIED_LIST 307
#define ASN1_XNAP_ID_TRAFFIC_REQUIRED_TO_BE_MODIFIED_LIST 308
#define ASN1_XNAP_ID_TRAFFIC_REQUIRED_MODIFIED_LIST 309
#define ASN1_XNAP_ID_TRAFFIC_RELEASED_LIST 310
#define ASN1_XNAP_ID_IAB_TNL_ADDRESS_TO_BE_ADDED 311
#define ASN1_XNAP_ID_IAB_TNL_ADDRESS_TO_BE_RELEASED_LIST 312
#define ASN1_XNAP_ID_NON_F1_TERMINATING_IAB_DONOR_UE_XN_AP_ID 313
#define ASN1_XNAP_ID_F1_TERMINATING_IAB_DONOR_UE_XN_AP_ID 314
#define ASN1_XNAP_ID_BOUNDARY_NODE_CELLS_LIST 315
#define ASN1_XNAP_ID_PARENT_NODE_CELLS_LIST 316
#define ASN1_XNAP_ID_TDD_GNB_DU_CELL_RES_CFG 317
#define ASN1_XNAP_ID_UL_GNB_DU_CELL_RES_CFG 318
#define ASN1_XNAP_ID_DL_GNB_DU_CELL_RES_CFG 319
#define ASN1_XNAP_ID_PERMUTATION 320
#define ASN1_XNAP_ID_IAB_TNL_ADDRESS_EXCEPTION 321
#define ASN1_XNAP_ID_CH_OINFO_ADD_REQ 322
#define ASN1_XNAP_ID_CH_OINFO_MOD_REQ 323
#define ASN1_XNAP_ID_SURVIVAL_TIME 324
#define ASN1_XNAP_ID_TIME_SYNC_ASSIST_INFO 325
#define ASN1_XNAP_ID_SCG_ACTIVATION_REQUEST 326
#define ASN1_XNAP_ID_SCG_ACTIVATION_STATUS 327
#define ASN1_XNAP_ID_CP_A_INFO_REQUEST 328
#define ASN1_XNAP_ID_CP_A_INFO_ACK 329
#define ASN1_XNAP_ID_C_PCI_NFORMATION_REQUIRED 330
#define ASN1_XNAP_ID_C_PCI_NFORMATION_CONFIRM 331
#define ASN1_XNAP_ID_CP_A_INFO_MOD_REQ 332
#define ASN1_XNAP_ID_CP_A_INFO_MOD_REQ_ACK 333
#define ASN1_XNAP_ID_CP_C_DATA_FORWARDING_IND 334
#define ASN1_XNAP_ID_C_PCI_NFORMATION_UPD 335
#define ASN1_XNAP_ID_CP_AC_INFO_MOD_REQUIRED 336
#define ASN1_XNAP_ID_Q_MCC_ONFIG_INFO 337
#define ASN1_XNAP_ID_PROTOCOL_IE_ID338_NOT_TO_BE_USED 338
#define ASN1_XNAP_ID_ADD_MEAS_TIMING_CFG_LIST 339
#define ASN1_XNAP_ID_PDU_SESSION_PAIR_ID 340
#define ASN1_XNAP_ID_LOCAL_NG_RAN_NODE_ID 341
#define ASN1_XNAP_ID_NEIGHBOUR_NG_RAN_NODE_LIST 342
#define ASN1_XNAP_ID_LOCAL_NG_RAN_NODE_ID_REMOVAL 343
#define ASN1_XNAP_ID_FIVE_G_PRO_SE_AUTHORIZED 344
#define ASN1_XNAP_ID_FIVE_G_PRO_SE_PC5_QOS_PARAMS 345
#define ASN1_XNAP_ID_FIVE_G_PRO_SE_UE_PC5_AGGR_MAX_BIT_RATE 346
#define ASN1_XNAP_ID_SERVED_CELL_SPECIFIC_INFO_REQ_NR 347
#define ASN1_XNAP_ID_NR_PAGINGE_DRX_INFO 348
#define ASN1_XNAP_ID_NR_PAGINGE_DRX_INFOFOR_RRC_INACTIVE 349
#define ASN1_XNAP_ID_REDCAP_BCAST_INFO 350
#define ASN1_XNAP_ID_SDT_SUPPORT_REQUEST 351
#define ASN1_XNAP_ID_SDT_SRB_BETWEEN_NEW_NODE_OLD_NODE 352
#define ASN1_XNAP_ID_SDT_TERMINATION_REQUEST 353
#define ASN1_XNAP_ID_SDT_PARTIAL_UE_CONTEXT_INFO 354
#define ASN1_XNAP_ID_SDT_DATA_FORWARDING_DRB_LIST 355
#define ASN1_XNAP_ID_PAGING_CAUSE 356
#define ASN1_XNAP_ID_PE_IP_SASSIST_INFO 357
#define ASN1_XNAP_ID_UE_SLICE_MAX_BIT_RATE_LIST 358
#define ASN1_XNAP_ID_S_NG_RA_NNODE_UE_SLICE_MBR 359
#define ASN1_XNAP_ID_POSITIONING_INFO 360
#define ASN1_XNAP_ID_UE_ASSISTANT_ID 361
#define ASN1_XNAP_ID_MANAGEMENT_BASED_MDT_PLMN_MOD_LIST 362
#define ASN1_XNAP_ID_F1_TERMINATING_IAB_DONOR_IND 363
#define ASN1_XNAP_ID_TAI_NSAG_SUPPORT_LIST 364
#define ASN1_XNAP_ID_SC_GRECFG_NOTIF 365
#define ASN1_XNAP_ID_EARLY_MEAS 366
#define ASN1_XNAP_ID_BEAM_MEASS_REPORT_CFG 367
#define ASN1_XNAP_ID_COVERAGE_MOD_CAUSE 368
#define ASN1_XNAP_ID_ADD_LISTOF_PDU_SESSION_RES_CHANGE_CONFIRM_INFO_SN_TERMINATED 369
#define ASN1_XNAP_ID_UE_RLF_REPORT_CONTAINER_LTE_EXT 370
#define ASN1_XNAP_ID_EXCESS_PACKET_DELAY_THRES_CFG 371
#define ASN1_XNAP_MAX_PRIVATE_IES 65535
#define ASN1_XNAP_MAX_PROTOCOL_EXTS 65535
#define ASN1_XNAP_MAX_PROTOCOL_IES 65535

/*******************************************************************************
 *                              Struct Definitions
 ******************************************************************************/

// PrivateIE-ID ::= CHOICE
struct private_ie_id_c {
  struct types_opts {
    enum options { local, global, nulltype } value;

    const char* to_string() const;
  };
  using types = enumerated<types_opts>;

  // choice methods
  private_ie_id_c() = default;
  void        set(types::options e = types::nulltype);
  types       type() const { return type_; }
  SRSASN_CODE pack(bit_ref& bref) const;
  SRSASN_CODE unpack(cbit_ref& bref);
  void        to_json(json_writer& j) const;
  // getters
  uint32_t& local()
  {
    assert_choice_type(types::local, type_, "PrivateIE-ID");
    return c;
  }
  const uint32_t& local() const
  {
    assert_choice_type(types::local, type_, "PrivateIE-ID");
    return c;
  }
  uint32_t& set_local();
  void      set_global();

private:
  types    type_;
  uint32_t c;
};

// PrivateIE-Field{XNAP-PRIVATE-IES : IEsSetParam} ::= SEQUENCE{{XNAP-PRIVATE-IES}}
template <class ies_set_paramT_>
struct private_ie_field_s {
  private_ie_id_c                   id;
  crit_e                            crit;
  typename ies_set_paramT_::value_c value;

  SRSASN_CODE pack(bit_ref& bref) const;
  SRSASN_CODE unpack(cbit_ref& bref);
  void        to_json(json_writer& j) const;
};

// PrivateIE-Container{XNAP-PRIVATE-IES : IEsSetParam} ::= SEQUENCE (SIZE (1..65535)) OF PrivateIE-Field
template <class ies_set_paramT_>
using private_ie_container_l = dyn_seq_of<private_ie_field_s<ies_set_paramT_>, 1, 65535, true>;

template <class valueT_>
struct private_ie_container_item_s {
  private_ie_id_c id;
  crit_e          crit;
  valueT_         value;

  // sequence methods
  private_ie_container_item_s(private_ie_id_c id_, crit_e crit_);
  SRSASN_CODE pack(bit_ref& bref) const;
  SRSASN_CODE unpack(cbit_ref& bref);
  void        to_json(json_writer& j) const;
};

} // namespace xnap
} // namespace asn1
