include:
  - project: softwareradiosystems/testing-tools
    ref: "37"
    file: .gitlab/ci-shared/setup/all.yml

stages:
  - build and unit tests

# Template job

.build_and_unit:
  image: ${CR_REGISTRY_URI}/${PROJECT}/srs-builder-gnb-${OS}:${DOCKER_BUILDER_VERSION}
  tags:
    - ${SRS_INFRASTRUCTURE_TAG}-${PLATFORM}
  stage: build and unit tests
  variables:
    DOCKER_BUILDER_VERSION: "1.7.4"
    # General
    OS: ubuntu-22.04
    # Build
    COMPILER: gcc
    UHD_VERSION: "" # Empty for OS default
    BUILD_TYPE: "" # Empty for cmake default
    ASSERT_LEVEL: "" # Empty for cmake default
    ENABLE_EXPORT: "" # Empty for cmake default
    ENABLE_FFTW: "" # Empty for cmake default
    ENABLE_UHD: "" # Empty for cmake default
    ENABLE_ZERO_MQ: "" # Empty for cmake default
    ENABLE_ASAN: "" # Empty for cmake default
    ENABLE_TSAN: "" # Empty for cmake default
    ENABLE_GCOV: "" # Empty for cmake default
    AUTO_DETECT_ISA: "False"
    PLATFORM: "amd64"
    PROJECT: "testing-tools"
    # Test
    TEST_MODE: none # default, coverage, asan, tsan, valgrind, none
  needs: []
  before_script:
    - |
      build_srsgnb() {
        if [ -n "${UHD_VERSION}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -u ${UHD_VERSION}"
        fi
        if [ -n "${BUILD_TYPE}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}"
        fi
        if [ -n "${ASSERT_LEVEL}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DASSERT_LEVEL=${ASSERT_LEVEL}"
        fi
        if [ -n "${AUTO_DETECT_ISA}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DAUTO_DETECT_ISA=${AUTO_DETECT_ISA}"
        fi
        if [ -n "${ENABLE_EXPORT}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_EXPORT=${ENABLE_EXPORT}"
        fi
        if [ -n "${ENABLE_FFTW}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_FFTW=${ENABLE_FFTW}"
        fi
        if [ -n "${ENABLE_UHD}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_UHD=${ENABLE_UHD}"
        fi
        if [ -n "${ENABLE_ZERO_MQ}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_ZERO_MQ=${ENABLE_ZERO_MQ}"
        fi
        if [ -n "${ENABLE_ASAN}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_ASAN=${ENABLE_ASAN}"
        fi
        if [ -n "${ENABLE_TSAN}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_TSAN=${ENABLE_TSAN}"
        fi
        if [ -n "${ENABLE_GCOV}" ]; then
          BUILD_ARGS="${BUILD_ARGS} -DENABLE_GCOV=${ENABLE_GCOV}"
        fi
        if [[ $TEST_MODE = "none" ]]; then
          BUILD_ARGS="${BUILD_ARGS} -DBUILD_TESTS=False"
        fi

        BUILD_CMD="builder.sh -c ${COMPILER} ${BUILD_ARGS} ."
        echo "${BUILD_CMD}"
        echo "============================================================================================="
        $BUILD_CMD
      }
    - |
      launch_tests() {
        cd ${CI_PROJECT_DIR}/build
        case $TEST_MODE in
          none)
            echo "Tests skipped"
            exit 0
            ;;
          tsan)
            ctest_extra="-L tsan"
            ;;
          valgrind)
            cp DartConfiguration.tcl ${test_folder}/
            sed -i "s/${CI_PROJECT_DIR//\//\\/}\/build/${CI_PROJECT_DIR//\//\\/}\/build\/${test_folder//\//\\/}/" ${test_folder}/DartConfiguration.tcl
            sed -i "s/MemoryCheckCommandOptions: /MemoryCheckCommandOptions: --verbose --trace-children=yes --time-stamp=yes --leak-check=full --show-leak-kinds=all --show-reachable=yes/" ${test_folder}/DartConfiguration.tcl
            G_DEBUG=gc-friendly G_SLICE=always-malloc
            ctest_extra="-T memcheck --timeout 10800"
            ;;
        esac
        CTEST_CMD="ctest -j "$(nproc --all)" $ctest_extra --schedule-random --output-on-failure --output-junit xunit.xml"
        echo "${CTEST_CMD}"
        echo "============================================================================================="
        $CTEST_CMD && ret=0 || ret=1

        if [[ $TEST_MODE = "coverage" ]]; then 
          gcovr --xml --print-summary -j "$(nproc --all)" --exclude-unreachable-branches \
            --gcov-ignore-parse-errors \
            --exclude "${CI_PROJECT_DIR}/unittests/*" \
            --exclude "${CI_PROJECT_DIR}/integrationtests /*" \
            --exclude "${CI_PROJECT_DIR}/benchmarks/*" \
            --exclude "${CI_PROJECT_DIR}/apps/examples/*" \
            --exclude "${CI_PROJECT_DIR}/external/*" \
            --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/e1ap/.*" \
            --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/f1ap/.*" \
            --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/ngap/.*" \
            --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/rrc_nr/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/asn1/e1ap/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/asn1/f1ap/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/asn1/ngap/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/asn1/rrc_nr/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/phy/generic_functions/fftx/lib_fftx_dftbat_srcs/.*" \
            --exclude "${CI_PROJECT_DIR}/lib/phy/generic_functions/fftx/lib_fftx_idftbat_srcs/.*" \
            --exclude-lines-by-pattern ".*srsgnb_assert.*|.*srsgnb_sanity_check.*" \
            --root ${CI_PROJECT_DIR} \
            -o coverage.xml

          filesize=$(stat -c%s coverage.xml)
          maxsize=$((10*1204*1024))
          (( filesize > maxsize )) && echo "coverage.xml is greater than 10MB, over gitlab limit" && exit 1
        fi
        exit $ret
      }
  script:
    - build_srsgnb
    - launch_tests
  after_script:
    - mv ${CI_PROJECT_DIR}/build/xunit.xml         ${CI_PROJECT_DIR}/${CI_JOB_ID}_xunit.xml               || true
    - mv ${CI_PROJECT_DIR}/build/coverage.xml      ${CI_PROJECT_DIR}/${CI_JOB_ID}_coverage.xml            || true
    - mv ${CI_PROJECT_DIR}/build/Testing/Temporary ${CI_PROJECT_DIR}/build/Testing/Temporary_${CI_JOB_ID} || true
  artifacts:
    when: always
    reports:
      junit: ${CI_JOB_ID}_xunit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${CI_JOB_ID}_coverage.xml
    paths:
      - ${CI_JOB_ID}_xunit.xml
      - ${CI_JOB_ID}_coverage.xml
      - build/Testing/Temporary_${CI_JOB_ID}
      - build/apps/gnb/gnb
    expire_in: 10 minutes
  cache: &build_cache
    key: ${OS}-${DOCKER_BUILDER_VERSION}-${COMPILER}
    paths:
      - ccache
    policy: pull

.build_and_unit_big:
  extends: .build_and_unit
  variables:
    KUBERNETES_CPU_REQUEST: 7
    KUBERNETES_MEMORY_REQUEST: 13Gi

# Main combinations

.build_and_unit_main:
  extends: .build_and_unit_big
  variables:
    ASSERT_LEVEL: PARANOID
  parallel:
    matrix:
      - OS: ubuntu-22.04
        TEST_MODE: coverage
        COMPILER: gcc
        BUILD_TYPE: Release
        ENABLE_GCOV: "True"
      - OS: archlinux-latest
        TEST_MODE: default
        COMPILER: gcc
        BUILD_TYPE: Release
      - OS: ubuntu-20.04
        TEST_MODE: default
        COMPILER: gcc
        BUILD_TYPE: Release
        ENABLE_EXPORT: "True"
      - OS: rhel8
        TEST_MODE: default
        COMPILER: gcc
        BUILD_TYPE: Release

build cached:
  extends: .build_and_unit_main
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      when: never
    - if: $ON_MR
  cache:
    <<: *build_cache
    policy: pull

build update cache:
  extends: .build_and_unit_main
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      when: never
    - if: $CI_DESCRIPTION =~ /Nightly/
  cache:
    <<: *build_cache
    policy: push

build clean:
  extends: .build_and_unit_main
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
  cache: []

# Alt combinations

.build_and_unit_alt:
  extends: .build_and_unit
  variables:
    OS: "" # Need to be specified
  parallel:
    matrix:
      - TEST_MODE: default
        COMPILER: [gcc, clang]
        BUILD_TYPE: [Debug, Release]
        ASSERT_LEVEL: [MINIMAL, NORMAL, PARANOID]
        ENABLE_EXPORT: ["True", "False"]
        ENABLE_GCOV: "False"
        ENABLE_ASAN: "False"
        ENABLE_TSAN: "False"

build alt [ubuntu 22.04 amd64]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: ubuntu-22.04
  cache: []

build alt [ubuntu 22.04 arm64v8]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Weekly/
  variables:
    OS: ubuntu-22.04
    PLATFORM: "arm64"
  cache: []

build alt [archlinux-latest amd64]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: archlinux-latest
  cache: []

build alt [ubuntu-20.04 amd64]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: ubuntu-20.04
  cache: []

build alt [ubuntu-20.04 arm64v8]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Weekly/
  variables:
    OS: ubuntu-20.04
    PLATFORM: "arm64"
  cache: []

build alt [rhel8-latest amd64]:
  extends: .build_and_unit_alt
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: rhel8
  cache: []

# UHD

build uhd alt:
  extends: .build_and_unit
  rules:
    - if: $CI_DESCRIPTION =~ /Weekly/
  variables:
    TEST_MODE: none
    ASSERT_LEVEL: PARANOID
  parallel:
    matrix:
      - OS: ubuntu-22.04
        COMPILER: [gcc, clang]
        UHD_VERSION: "4.2.0.0"
      - OS: ubuntu-20.04
        COMPILER: [gcc, clang]
        UHD_VERSION: ["4.2.0.0", "4.1.0.5"]
  cache: []

# Sanitizers
sanitizers [asan]:
  extends: .build_and_unit
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: ubuntu-22.04
    TEST_MODE: asan
    COMPILER: gcc
    BUILD_TYPE: Debug
    ENABLE_ASAN: "True"
    ASSERT_LEVEL: PARANOID
  cache: []

sanitizers [tsan]:
  extends: .build_and_unit
  rules:
    - if: $CI_DESCRIPTION =~ /Nightly/
  variables:
    OS: ubuntu-22.04
    TEST_MODE: tsan
    COMPILER: clang
    BUILD_TYPE: Debug
    ENABLE_TSAN: "True"
    ASSERT_LEVEL: PARANOID
  cache: []

sanitizers [valgrind]:
  extends: .build_and_unit
  rules:
    - if: $CI_DESCRIPTION =~ /Weekly/
  variables:
    OS: ubuntu-22.04
    TEST_MODE: valgrind
    COMPILER: gcc
    BUILD_TYPE: Debug
    ASSERT_LEVEL: PARANOID
  cache: []
  timeout: 4 hours # valgrind mode

# AVX

.avx_compability:
  extends: .build_and_unit
  tags:
    - aws-demand-amd64-$CPU_FLAG
  variables:
    OS: ubuntu-22.04
    TEST_MODE: coverage
    COMPILER: gcc
    BUILD_TYPE: Release

avx compatibility:
  extends: .avx_compability
  rules:
    - if: $ON_MR
      when: manual
      allow_failure: true
    - if: $CI_DESCRIPTION =~ /Nightly/
  parallel:
    matrix:
      - CPU_FLAG: "avx2"
        AUTO_DETECT_ISA: "True"
        ENABLE_AVX512: "False"
        ENABLE_AVX2: "True"
      - CPU_FLAG: "avx2-avx512"
        AUTO_DETECT_ISA: "True"
        ENABLE_AVX512: "True"
        ENABLE_AVX2: "True"

avx compatibility extended:
  extends: .avx_compability
  rules:
    - if: $CI_DESCRIPTION =~ /Weekly/
  parallel:
    matrix:
      - CPU_FLAG: ["avx2", "avx2-avx512"]
        AUTO_DETECT_ISA: ["True", "False"]
        ENABLE_AVX512: ["True", "False"]
        ENABLE_AVX2: ["True", "False"]

# Custom

custom build [amd64]:
  tags:
    - aws-spot-arm64
  extends: .build_and_unit
  rules:
    - if: $ON_MR
  variables:
    # must be one of ubuntu-22.04, ubuntu-20.04, archlinux-latest
    OS: "ubuntu-22.04"
    # must be one of gcc, clang
    COMPILER: "gcc"
    # must be one of default, coverage, asan, tsan, valgrind, none
    TEST_MODE: "default"
    # it will be passed to cmake
    BUILD_ARGS: ""
    # must be one version supported in the specified OS
    UHD_VERSION: ""
  cache: []
  timeout: 4 hours # valgrind mode

custom build [arm64v8]:
  extends: custom build [amd64]
  rules:
    - if: $ON_MR
  variables:
    PLATFORM: "arm64"
